[package]
edition = "2024"
name = "tpuart_bridge"
version = "0.1.0"

[dependencies]
embassy-executor = { version = "0.7", features = ["nightly", "arch-cortex-m", "executor-thread", "defmt"] }
embassy-time = { version = "0.4", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-stm32 = { version = "0.2", features = ["defmt", "stm32f103c8", "unstable-pac", "memory-x", "time-driver-any"]  }

defmt = "1.0"
defmt-macros = "1.0"
defmt-rtt = "1.0"

cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
embedded-hal = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }
futures = { version = "0.3", default-features = false, features = ["async-await"] }
embedded-io-async = { version = "0.6" }
static-alloc = "0.2"

[profile.dev]
opt-level = "s"

[profile.release]
opt-level = "s"
strip = "none"
debug = 2
