//! System B Demo Device Definition
//!
//! Complete device definition for a KNX/IP System B demo device.
//! This module contains everything needed to define the device for
//! both runtime and ETS export purposes.

use core::net::Ipv4Addr;

use const_default::ConstDefault;
use serde::{Deserialize, Serialize};

use zweidraehte_knxprod::definition::page_layout::{EtsPageLayout, PageStructure};
use zweidraehte_knxprod::ets_pages;
/// Big-endian u16 for KNX parameter storage.
///
/// KNX stores multi-byte parameters in big-endian format (network byte order).
/// This wrapper type stores the value in big-endian and provides serde support.
#[derive(Debug, Clone, Copy)]
#[repr(transparent)]
pub struct BeU16([u8; 2]);

impl BeU16 {
    pub const fn new(value: u16) -> Self {
        Self(value.to_be_bytes())
    }

    pub const fn get(&self) -> u16 {
        u16::from_be_bytes(self.0)
    }
}

impl const_default::ConstDefault for BeU16 {
    const DEFAULT: Self = Self::new(0);
}

impl serde::Serialize for BeU16 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        self.get().serialize(serializer)
    }
}

impl<'de> serde::Deserialize<'de> for BeU16 {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = u16::deserialize(deserializer)?;
        Ok(Self::new(value))
    }
}

impl core::fmt::Display for BeU16 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.get())
    }
}
use zweidraehte_device::bcus::system_b::{
    HasPersistedState, IpDeviceState, IpExtension, SystemBInterfaceObjectsFor, SystemBMemoryMap,
    SystemBStackDefinition, create_system_b_objects_from_extension,
};
use zweidraehte_device::dpt::*;
use zweidraehte_device::layers::linklayers::knxip::{KnxNetIpBuilder, features::KnxIpDeviceTcp};
use zweidraehte_device::layers::transport::TlStyle;
use zweidraehte_device::prelude::*;
use zweidraehte_platform::LinuxIpTransport;

// ============================================================================
// Device Descriptor
// ============================================================================

/// Device descriptor - single source of truth for device metadata.
pub const DEVICE_DESCRIPTOR: DeviceDescriptor = DeviceDescriptor {
    mask_version: MaskVersion::SystemBKnxIp,
    manufacturer_id: 0x00FA,
    hardware_type: [0x00, 0x00, 0x00, 0x00, 0x00, 0x02],
    application_id: 0x0200,
    application_version: 0x01,
    max_address_table_entries: 16,
    max_association_table_entries: 16,
    max_com_objects: 8,
    pei_type: 0,
};

/// Serial number for test device.
pub const SERIAL_NUMBER: [u8; 6] = [0x00, 0xFA, 0xDE, 0xAD, 0xBE, 0xEF];

/// Network interface name for KNX/IP communication.
pub const INTERFACE_NAME: &str = "knxdevbridgeif";

// ============================================================================
// Channel Mode Selector (for ComObjectRef demo)
// ============================================================================

/// Channel output mode - controls which DPT the output comm object uses.
///
/// This enum is used as a selector for ComObjectRefs. In ETS, when the user
/// changes the channel mode parameter, the comm object's DPT changes accordingly:
/// - Switch mode: DPT_Switch (1 bit)
/// - Dimmer mode: DPT_Value_1_Ucount (8 bit, 0-255)
/// - Blind mode: DPT_Value_1_Ucount (8 bit, 0-100% position)
#[derive(Debug, Clone, Copy, PartialEq, Eq, EtsEnum, Serialize, Deserialize)]
#[repr(u8)]
pub enum ChannelMode {
    /// Disabled - no output
    #[ets(display = "Disabled")]
    Disabled = 0,

    /// Switch mode - on/off control
    #[ets(display = "Switch")]
    Switch = 1,

    /// Dimmer mode - 0-100% brightness
    #[ets(display = "Dimmer")]
    Dimmer = 2,

    /// Blind/shutter mode - position control
    #[ets(display = "Blind")]
    Blind = 3,
}

impl ConstDefault for ChannelMode {
    const DEFAULT: Self = Self::Disabled;
}

// ============================================================================
// Communication Objects
// ============================================================================

pub mod comm_objs {
    use super::*;
    // Import the discriminant enum generated by EtsUnion derive macro
    use super::OutputConfigDiscriminant;
    use zweidraehte_device::objects::comm::ComObjectStorage;

    /// Demo communication objects showcasing ComObjectRefs.
    ///
    /// This struct demonstrates how comm objects can have different DPT interpretations
    /// based on parameter values. In ETS:
    ///
    /// - When `channel_a_config = Switch`, `channel_a_output` shows as DPT 1.001 (Switch)
    /// - When `channel_a_config = Dimmer`, `channel_a_output` shows as DPT 5.001 (Scaling)
    /// - When `channel_a_config = Pwm`, `channel_a_output` shows as DPT 5.001 (Scaling)
    ///
    /// The `#[ets_ref]` attributes define alternative views of the same physical object.
    /// Use `OutputConfigDiscriminant::*` variants in `when` clauses to specify which
    /// discriminant value activates each ref.
    #[derive(EtsComObjects)]
    pub struct DemoComObjects {
        // ====================================================================
        // Channel A: Multi-mode output with ComObjectRefs
        // The selector_param references the union selector (channel_a_config_selector)
        // which is auto-generated from the union field name.
        // Use OutputConfigDiscriminant::* for type-safe discriminant values.
        // ====================================================================
        /// Channel A input - receives control commands
        /// DPT changes based on channel_a_config union selector.
        /// Storage size 1 = max(sizeof(DPT_Switch)=1, sizeof(DPT_Value_1_Ucount)=1)
        #[ets(
            index = 1,
            display = "Channel A Input",
            function = "Control input",
            selector_param = "channel_a_config_selector"
        )]
        #[ets_ref(dpt = DPT_Switch, when = OutputConfigDiscriminant::Switch, function = "Switch on/off")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Dimmer, function = "Dim value 0-255")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Pwm, function = "PWM value")]
        pub channel_a_in: ComObject<ComObjectStorage<1>>,

        /// Channel A output - sends current state to bus
        /// DPT changes based on channel_a_config union selector
        #[ets(
            index = 2,
            display = "Channel A Output",
            function = "Status output",
            flags = C | R | W | T | LOW,
            selector_param = "channel_a_config_selector"
        )]
        #[ets_ref(dpt = DPT_Switch, when = OutputConfigDiscriminant::Switch, function = "Switch state")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Dimmer, function = "Brightness level")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Pwm, function = "PWM level")]
        pub channel_a_out: ComObject<ComObjectStorage<1>>,

        // ====================================================================
        // Channel B: Multi-mode output with ComObjectRefs
        // ====================================================================
        /// Channel B input - receives control commands
        #[ets(
            index = 3,
            display = "Channel B Input",
            function = "Control input",
            selector_param = "channel_b_config_selector"
        )]
        #[ets_ref(dpt = DPT_Switch, when = OutputConfigDiscriminant::Switch, function = "Switch on/off")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Dimmer, function = "Dim value 0-255")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Pwm, function = "PWM value")]
        pub channel_b_in: ComObject<ComObjectStorage<1>>,

        /// Channel B output - sends current state to bus
        #[ets(
            index = 4,
            display = "Channel B Output",
            function = "Status output",
            flags = C | R | W | T | LOW,
            selector_param = "channel_b_config_selector"
        )]
        #[ets_ref(dpt = DPT_Switch, when = OutputConfigDiscriminant::Switch, function = "Switch state")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Dimmer, function = "Brightness level")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Pwm, function = "PWM level")]
        pub channel_b_out: ComObject<ComObjectStorage<1>>,

        // ====================================================================
        // Fixed-type objects (no ComObjectRefs)
        // ====================================================================
        /// Scene control input - receives scene recall/store commands
        #[ets(index = 5, display = "Scene Control", function = "Scene recall/store (DPT 17.001)")]
        pub scene_control: ComObject<DPT_Value_1_Ucount>,

        /// Lock input - enables/disables output locking
        #[ets(index = 6, display = "Lock", function = "Output lock control")]
        pub lock_in: ComObject<DPT_Switch>,

        /// General status output - always a switch type
        #[ets(index = 7, display = "In Operation", function = "Device in operation status", flags = C | W | T | LOW)]
        pub in_operation: ComObject<DPT_Switch>,

        /// Error status output
        #[ets(index = 8, display = "Error", function = "Error status output", flags = C | W | T | LOW)]
        pub error_status: ComObject<DPT_Switch>,
    }
}

// ============================================================================
// Application Parameters
// ============================================================================

// ----------------------------------------------------------------------------
// Simple enums for use in EtsUnion variants (type-safe, matchable in Rust)
// ----------------------------------------------------------------------------

/// Analog input type selector.
#[derive(Debug, Clone, Copy, PartialEq, Eq, EtsEnum, Serialize, Deserialize)]
#[repr(u8)]
pub enum AnalogInputType {
    #[ets(display = "0-10V")]
    Voltage0_10V = 0,
    #[ets(display = "4-20mA")]
    Current4_20mA = 1,
}

impl ConstDefault for AnalogInputType {
    const DEFAULT: Self = Self::Voltage0_10V;
}

/// Temperature sensor type selector.
#[derive(Debug, Clone, Copy, PartialEq, Eq, EtsEnum, Serialize, Deserialize)]
#[repr(u8)]
pub enum SensorType {
    #[ets(display = "PT100")]
    Pt100 = 0,
    #[ets(display = "PT1000")]
    Pt1000 = 1,
    #[ets(display = "NTC 10K")]
    Ntc10K = 2,
}

impl ConstDefault for SensorType {
    const DEFAULT: Self = Self::Pt100;
}

/// Yes/No boolean selector for invert options.
#[derive(Debug, Clone, Copy, PartialEq, Eq, EtsEnum, Serialize, Deserialize)]
#[repr(u8)]
pub enum YesNo {
    #[ets(display = "No")]
    No = 0,
    #[ets(display = "Yes")]
    Yes = 1,
}

impl ConstDefault for YesNo {
    const DEFAULT: Self = Self::No;
}

impl From<bool> for YesNo {
    fn from(value: bool) -> Self {
        if value { Self::Yes } else { Self::No }
    }
}

impl From<YesNo> for bool {
    fn from(value: YesNo) -> Self {
        matches!(value, YesNo::Yes)
    }
}

// ----------------------------------------------------------------------------
// EtsUnion enums (with data fields)
// ----------------------------------------------------------------------------

/// Demo union for testing ETS union export.
///
/// The `#[derive(EtsUnion)]` macro generates:
/// - `ETS_UNION_INFO`: Union metadata including variant parameters
/// - `ETS_SELECTOR_VARIANTS`: Enum variants for the discriminant/selector
/// - `EtsUnionType` trait implementation
#[derive(Debug, Clone, Copy, EtsUnion, Serialize, Deserialize)]
#[repr(C, u8)]
pub enum OutputConfig {
    /// Output disabled
    #[ets(display = "Disabled")]
    Disabled = 0,

    /// Switch output mode
    #[ets(display = "Switch Mode")]
    Switch {
        /// Invert the switch output
        #[ets(display = "Invert Output", ets_enum)]
        invert: YesNo,
    },

    /// Dimmer output mode
    #[ets(display = "Dimmer Mode")]
    Dimmer {
        /// Minimum dimmer level (0-100%)
        #[ets(display = "Min Level")]
        min_level: u8,
        /// Maximum dimmer level (0-100%)
        #[ets(display = "Max Level")]
        max_level: u8,
    },

    /// PWM output mode
    #[ets(display = "PWM Mode")]
    Pwm {
        /// PWM frequency in Hz
        #[ets(display = "Frequency")]
        frequency: BeU16,
        /// PWM duty cycle (0-100%)
        #[ets(display = "Duty Cycle")]
        duty_cycle: u8,
    },
}

impl ConstDefault for OutputConfig {
    const DEFAULT: Self = OutputConfig::Disabled;
}

/// Input source configuration union.
///
/// Demonstrates a union with different input types, each with their own parameters.
#[derive(Debug, Clone, Copy, EtsUnion, Serialize, Deserialize)]
#[repr(C, u8)]
pub enum InputSource {
    /// No input source configured
    #[ets(display = "None")]
    None = 0,

    /// Binary input (digital)
    #[ets(display = "Binary Input")]
    Binary {
        /// Debounce time in milliseconds
        #[ets(display = "Debounce Time")]
        debounce_ms: BeU16,
        /// Invert input logic
        #[ets(display = "Invert", ets_enum)]
        invert: YesNo,
    },

    /// Analog input (0-10V or 4-20mA)
    #[ets(display = "Analog Input")]
    Analog {
        /// Input type
        #[ets(display = "Input Type", ets_enum)]
        input_type: AnalogInputType,
        /// Low threshold value
        #[ets(display = "Low Threshold")]
        low_threshold: BeU16,
        /// High threshold value
        #[ets(display = "High Threshold")]
        high_threshold: BeU16,
    },

    /// Temperature sensor input
    #[ets(display = "Temperature Sensor")]
    Temperature {
        /// Sensor type
        #[ets(display = "Sensor Type", ets_enum)]
        sensor_type: SensorType,
        /// Offset calibration in 0.1°C
        #[ets(display = "Offset")]
        offset: i8,
    },
}

impl ConstDefault for InputSource {
    const DEFAULT: Self = InputSource::None;
}

/// Scene configuration union.
///
/// Demonstrates a simple union for scene recall/store behavior.
#[derive(Debug, Clone, Copy, EtsUnion, Serialize, Deserialize)]
#[repr(C, u8)]
pub enum SceneConfig {
    /// Scene disabled
    #[ets(display = "Disabled")]
    Disabled = 0,

    /// Recall scene on trigger
    #[ets(display = "Recall Only")]
    RecallOnly {
        /// Scene number to recall (1-64)
        #[ets(display = "Scene Number")]
        scene_number: u8,
    },

    /// Store and recall scene
    #[ets(display = "Store & Recall")]
    StoreAndRecall {
        /// Scene number (1-64)
        #[ets(display = "Scene Number")]
        scene_number: u8,
        /// Long press time for store in 100ms units
        #[ets(display = "Store Time")]
        store_time: u8,
    },
}

impl ConstDefault for SceneConfig {
    const DEFAULT: Self = SceneConfig::Disabled;
}

/// Application parameters for the demo device.
///
/// The `#[derive(EtsParams)]` macro generates:
/// - `ETS_PARAMS`: Basic parameter definitions
/// - `ETS_PARAMS_EXT`: Extended definitions with enum variants
/// - `MODE_VARIANTS`: Auto-generated const for enum variants (named after the field)
/// - `ETS_UNIONS`: Union field information for union parameters
///
/// ## ComObjectRef Integration
///
/// The `channel_a_config` and `channel_b_config` union parameters control which
/// ComObjectRef is active for each channel. The union selector (e.g. "Switch Mode")
/// determines which variant-specific parameters are shown, AND which comm object
/// DPT is active.
///
/// Union fields can be placed anywhere in the struct. The macro uses `core::mem::offset_of!`
/// to correctly calculate field offsets regardless of union placement.
#[derive(Debug, Clone, Copy, EtsParams, Serialize, Deserialize)]
#[repr(C)]
pub struct DemoParams {
    /// Channel A output configuration - controls comm object DPT and mode-specific params
    #[ets(union, display = "Channel A Config")]
    pub channel_a_config: OutputConfig,

    /// Channel B output configuration
    #[ets(union, display = "Channel B Config")]
    pub channel_b_config: OutputConfig,

    /// Input source configuration
    #[ets(union, display = "Input Source")]
    pub input_source: InputSource,

    /// Scene configuration
    #[ets(union, display = "Scene Config")]
    pub scene_config: SceneConfig,

    /// Send cycle time in seconds (0 = disabled)
    #[ets(display = "Send Cycle Time", enum_variants("Disabled" => 0, "10s" => 10, "30s" => 30, "60s" => 60, "300s" => 300))]
    pub send_cycle_time: BeU16,

    /// Lock behavior with enum variants
    #[ets(display = "Lock Behavior", enum_variants("No Action" => 0, "Lock Off" => 1, "Lock On" => 2, "Lock Toggle" => 3))]
    pub lock_behavior: u8,
}

// ============================================================================
// Mock IP Platform
// ============================================================================

#[derive(Debug, Clone)]
pub struct MockIpPlatform {
    pub ip_address: Ipv4Addr,
    pub subnet_mask: Ipv4Addr,
    pub gateway: Ipv4Addr,
    pub mac_address: [u8; 6],
}

impl Default for MockIpPlatform {
    fn default() -> Self {
        Self {
            ip_address: Ipv4Addr::new(192, 168, 1, 200),
            subnet_mask: Ipv4Addr::new(255, 255, 255, 0),
            gateway: Ipv4Addr::new(192, 168, 1, 1),
            mac_address: [0xDE, 0xAD, 0xBE, 0xEF, 0xCA, 0xFE],
        }
    }
}

impl IpPlatform for MockIpPlatform {
    fn current_ip_address(&self) -> Ipv4Addr {
        self.ip_address
    }
    fn current_subnet_mask(&self) -> Ipv4Addr {
        self.subnet_mask
    }
    fn current_default_gateway(&self) -> Ipv4Addr {
        self.gateway
    }
    fn mac_address(&self) -> [u8; 6] {
        self.mac_address
    }
    fn current_ip_assignment_method(&self) -> u8 {
        0x02
    }
    fn ip_capabilities(&self) -> u8 {
        0x07
    }
}

impl zweidraehte_platform::NetworkConfig for MockIpPlatform {
    type Error = core::convert::Infallible;

    fn apply_ip_config(&self, _config: &zweidraehte_platform::IpConfig) -> Result<(), Self::Error> {
        Ok(()) // No-op — OS manages networking on Linux.
    }
}

// ============================================================================
// Stack Definition
// ============================================================================

const ADT_SIZE: usize = DEVICE_DESCRIPTOR.address_table_size();
const AST_SIZE: usize = DEVICE_DESCRIPTOR.association_table_size();
const COT_SIZE: usize = DEVICE_DESCRIPTOR.comm_object_table_size();

/// Unified state type.
pub type DemoState = IpDeviceState<ADT_SIZE, AST_SIZE, COT_SIZE, DemoStack, KnxIpDeviceTcp>;

/// Persisted snapshot type for the demo device.
pub type DemoPersistedState = <DemoState as HasPersistedState>::Persisted;

/// Configuration for constructing `DemoState` inside the runner.
///
/// Carries the device identity and an optional persisted snapshot.
/// If `persisted` is `None`, the state is initialized with factory defaults.
pub struct DemoStateConfig {
    pub serial: [u8; 6],
    pub fdsk: Option<[u8; 16]>,
    pub persisted: Option<DemoPersistedState>,
}

impl DemoStateConfig {
    /// Build config from a device identity and optional persisted snapshot.
    pub fn new(identity: &impl DeviceIdentity, persisted: Option<DemoPersistedState>) -> Self {
        Self {
            serial: *identity.serial_number(),
            fdsk: identity.fdsk().copied(),
            persisted,
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct DemoStack;

impl SystemBStackDefinition for DemoStack {}

impl StackDefinition for DemoStack {
    const DEVICE: &'static DeviceDescriptor = &DEVICE_DESCRIPTOR;
    const TL_STYLE: TlStyle = TlStyle::Style1;

    type P = DemoParams;
    type CO = comm_objs::DemoComObjects;
    type LLB = KnxNetIpBuilder<LinuxIpTransport, KnxIpDeviceTcp, 2>;
    type Platform = MockIpPlatform;
    type ES = IpExtension<KnxIpDeviceTcp>;
    type State = DemoState;
    type StateConfig = DemoStateConfig;
    type Mem = SystemBMemoryMap;

    fn create_state(config: Self::StateConfig) -> Self::State {
        use zweidraehte_device::storage::StaticIdentity;
        let identity = match config.fdsk {
            Some(fdsk) => StaticIdentity::with_fdsk(config.serial, fdsk),
            None => StaticIdentity::new(config.serial),
        };
        match config.persisted {
            Some(persisted) => DemoState::from_persisted(&identity, persisted),
            None => DemoState::new(&identity, comm_objs::DemoComObjects::new(), ()),
        }
    }

    type InterfaceObjects<'a> = SystemBInterfaceObjectsFor<'a, Self>;

    fn create_interface_objects<'a>(state: &'a Self::State, platform: &'a Self::Platform, _layer_ctx: &'a zweidraehte_device::layer_context::LayerContext<Self>) -> Self::InterfaceObjects<'a>
    where
        Self::State: 'a,
    {
        create_system_b_objects_from_extension::<Self>(state, platform, &Self::memory_layout())
    }

    type Services = (
        zweidraehte_device::layers::application::services::SystemBAlServices,
        zweidraehte_device::layers::application::services::DomainAddressService,
    );
    type LayerBuilder = InsecureIpDeviceBuilder;
}

// ============================================================================
// ETS Page Layout
// ============================================================================

impl EtsPageLayout for DemoStack {
    fn page_layout() -> PageStructure {
        use InputSourceDiscriminant::*;
        use OutputConfigDiscriminant::*;
        use SceneConfigDiscriminant::*;

        ets_pages! {
            // Device-wide settings shown at the top level (not in any channel tab)
            device {
                // General device behavior settings
                block "general" => "General" {
                    param send_cycle_time
                    sep "Scene Control"
                    selector scene_config
                    obj scene_control
                    sep "Lock"
                    param lock_behavior
                    obj lock_in
                }

                // Scene-specific settings appear conditionally
                // Using new path syntax: union_field::Variant.field
                when scene_config {
                    [RecallOnly] => {
                        block "scene_recall" => "    Scene Settings" {
                            param scene_config::RecallOnly.scene_number
                        }
                    }
                    [StoreAndRecall] => {
                        block "scene_store" => "    Scene Settings" {
                            param scene_config::StoreAndRecall.scene_number
                            param scene_config::StoreAndRecall.store_time
                        }
                    }
                }

                // Input source configuration
                block "input" => "Input" {
                    selector input_source
                }

                when input_source {
                    [Binary] => {
                        block "input_binary" => "    Binary Input Settings" {
                            param input_source::Binary.debounce_ms
                            param input_source::Binary.invert
                        }
                    }
                    [Analog] => {
                        block "input_analog" => "    Analog Input Settings" {
                            param input_source::Analog.input_type
                            sep "Thresholds"
                            param input_source::Analog.low_threshold
                            param input_source::Analog.high_threshold
                        }
                    }
                    [Temperature] => {
                        block "input_temp" => "    Temperature Sensor Settings" {
                            param input_source::Temperature.sensor_type
                            param input_source::Temperature.offset
                        }
                    }
                }

                // Status outputs (fixed, always visible)
                block "status" => "Status" {
                    obj in_operation
                    obj error_status
                }
            }

            // Outputs channel - groups output comm objects in Group Objects view
            channel "outputs" => "Outputs" (1) {
                // Output channel configuration - mode selectors
                block "output_config" => "Configuration" {
                    selector channel_a_config
                    selector channel_b_config
                }

                // Channel A config blocks appear below based on selection
                // The comm objects are conditional and will auto-wrap in choose/when
                when channel_a_config {
                    [Switch] => {
                        block "channel_a_switch" => "Channel A: Switch" {
                            param channel_a_config::Switch.invert
                            obj channel_a_in
                            obj channel_a_out
                        }
                    }
                    [Dimmer] => {
                        block "channel_a_dimmer" => "Channel A: Dimmer" {
                            param channel_a_config::Dimmer.min_level
                            param channel_a_config::Dimmer.max_level
                            obj channel_a_in
                            obj channel_a_out
                        }
                    }
                    [Pwm] => {
                        block "channel_a_pwm" => "Channel A: PWM" {
                            param channel_a_config::Pwm.frequency
                            param channel_a_config::Pwm.duty_cycle
                            obj channel_a_in
                            obj channel_a_out
                        }
                    }
                }

                // Channel B config blocks appear below based on selection
                when channel_b_config {
                    [Switch] => {
                        block "channel_b_switch" => "Channel B: Switch" {
                            param channel_b_config::Switch.invert
                            obj channel_b_in
                            obj channel_b_out
                        }
                    }
                    [Dimmer] => {
                        block "channel_b_dimmer" => "Channel B: Dimmer" {
                            param channel_b_config::Dimmer.min_level
                            param channel_b_config::Dimmer.max_level
                            obj channel_b_in
                            obj channel_b_out
                        }
                    }
                    [Pwm] => {
                        block "channel_b_pwm" => "Channel B: PWM" {
                            param channel_b_config::Pwm.frequency
                            param channel_b_config::Pwm.duty_cycle
                            obj channel_b_in
                            obj channel_b_out
                        }
                    }
                }
            }
        }
    }
}
