//! System B Demo Device Definition
//!
//! Device definition for a KNX/IP System B demo device: parameters,
//! communication objects, and the ETS page layout. It is kept as a
//! reference for ETS page-layout features not yet ported to the shared
//! `light_switch` definition; the MTXML generator
//! [`gen_mtxml`](../../../generators) renders it, and no firmware target
//! runs it (the Linux host targets run `light_switch` instead — see
//! `firmware/linux/eth_light_switch`).

use const_default::ConstDefault;
use serde::{Deserialize, Serialize};
use zerocopy::{Immutable, IntoBytes, KnownLayout};

use zweidraehte_knxprod::definition::page_layout::{EtsPageLayout, PageStructure};
use zweidraehte_knxprod::ets_pages;
/// Big-endian u16 for KNX parameter storage.
///
/// KNX stores multi-byte parameters in big-endian format (network byte order).
/// This wrapper type stores the value in big-endian and provides serde support.
#[derive(Debug, Clone, Copy, KnownLayout, Immutable, IntoBytes)]
#[repr(transparent)]
pub struct BeU16([u8; 2]);

impl BeU16 {
    pub const fn new(value: u16) -> Self {
        Self(value.to_be_bytes())
    }

    pub const fn get(&self) -> u16 {
        u16::from_be_bytes(self.0)
    }
}

impl const_default::ConstDefault for BeU16 {
    const DEFAULT: Self = Self::new(0);
}

impl serde::Serialize for BeU16 {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        self.get().serialize(serializer)
    }
}

impl<'de> serde::Deserialize<'de> for BeU16 {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let value = u16::deserialize(deserializer)?;
        Ok(Self::new(value))
    }
}

impl core::fmt::Display for BeU16 {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.get())
    }
}
use zweidraehte_device::prelude::*;
use zweidraehte_ets_model::{EtsComObjects, EtsEnum, ets_params, ets_union};
use zweidraehte_proto::dpt::*;

// ============================================================================
// Device Descriptor
// ============================================================================

/// Device descriptor - single source of truth for device metadata.
pub const DEVICE_DESCRIPTOR: DeviceDescriptor = DeviceDescriptor {
    mask_version: MaskVersion::SystemBKnxIp,
    manufacturer_id: 0x00FA,
    // The knxprod hardware serial and `PID_HARDWARE_TYPE` are the same
    // identifier (System 7 downloads verify the equality with
    // `LdCtrlCompareProp`; System B never checks, but the value must
    // not lie).
    hardware_type: SERIAL_NUMBER,
    application_id: 0x0200,
    application_version: 0x01,
    max_address_table_entries: 16,
    max_association_table_entries: 16,
    max_com_objects: 8,
    pei_type: 0,
};

/// Serial number for test device — also the device's hardware type.
pub const SERIAL_NUMBER: [u8; 6] = [0x00, 0xFA, 0xDE, 0xAD, 0xBE, 0xEF];

/// Device metadata anchor for the demo device.
///
/// Carries the transport-agnostic ETS artifacts (the [`EtsPageLayout`]
/// impl below). It is consumed only by the `gen_mtxml` generator; no
/// firmware target assembles a runnable `StackDefinition` from it (the
/// Linux host targets run the shared `light_switch` definition instead).
#[derive(Debug, Clone, Copy)]
pub struct SystemBDemoDevice;

// ============================================================================
// Channel Mode Selector (for ComObjectRef demo)
// ============================================================================

/// Channel output mode - controls which DPT the output comm object uses.
///
/// This enum is used as a selector for ComObjectRefs. In ETS, when the user
/// changes the channel mode parameter, the comm object's DPT changes accordingly:
/// - Switch mode: DPT_Switch (1 bit)
/// - Dimmer mode: DPT_Value_1_Ucount (8 bit, 0-255)
/// - Blind mode: DPT_Value_1_Ucount (8 bit, 0-100% position)
#[derive(Debug, Clone, Copy, PartialEq, Eq, EtsEnum, Serialize, Deserialize)]
#[repr(u8)]
pub enum ChannelMode {
    /// Disabled - no output
    #[ets(display = "Disabled")]
    Disabled = 0,

    /// Switch mode - on/off control
    #[ets(display = "Switch")]
    Switch = 1,

    /// Dimmer mode - 0-100% brightness
    #[ets(display = "Dimmer")]
    Dimmer = 2,

    /// Blind/shutter mode - position control
    #[ets(display = "Blind")]
    Blind = 3,
}

impl ConstDefault for ChannelMode {
    const DEFAULT: Self = Self::Disabled;
}

// ============================================================================
// Communication Objects
// ============================================================================

pub mod comm_objs {
    use super::*;
    // Import the discriminant enum generated by EtsUnion derive macro
    use super::OutputConfigDiscriminant;
    use zweidraehte_device::objects::comm::ComObjectStorage;

    /// Demo communication objects showcasing ComObjectRefs.
    ///
    /// This struct demonstrates how comm objects can have different DPT interpretations
    /// based on parameter values. In ETS:
    ///
    /// - When `channel_a_config = Switch`, `channel_a_output` shows as DPT 1.001 (Switch)
    /// - When `channel_a_config = Dimmer`, `channel_a_output` shows as DPT 5.001 (Scaling)
    /// - When `channel_a_config = Pwm`, `channel_a_output` shows as DPT 5.001 (Scaling)
    ///
    /// The `#[ets_ref]` attributes define alternative views of the same physical object.
    /// Use `OutputConfigDiscriminant::*` variants in `when` clauses to specify which
    /// discriminant value activates each ref.
    #[derive(EtsComObjects)]
    pub struct DemoComObjects {
        // ====================================================================
        // Channel A: Multi-mode output with ComObjectRefs
        // The selector_param references the union selector (channel_a_config_selector)
        // which is auto-generated from the union field name.
        // Use OutputConfigDiscriminant::* for type-safe discriminant values.
        // ====================================================================
        /// Channel A input - receives control commands
        /// DPT changes based on channel_a_config union selector.
        /// Storage size 1 = max(sizeof(DPT_Switch)=1, sizeof(DPT_Value_1_Ucount)=1)
        #[ets(
            index = 0,
            display = "Channel A Input",
            function = "Control input",
            selector_param = "channel_a_config_selector"
        )]
        #[ets_ref(dpt = DPT_Switch, when = OutputConfigDiscriminant::Switch, function = "Switch on/off")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Dimmer, function = "Dim value 0-255")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Pwm, function = "PWM value")]
        pub channel_a_in: ComObject<ComObjectStorage<1>>,

        /// Channel A output - sends current state to bus
        /// DPT changes based on channel_a_config union selector
        #[ets(
            index = 1,
            display = "Channel A Output",
            function = "Status output",
            flags = C | R | W | T | LOW,
            selector_param = "channel_a_config_selector"
        )]
        #[ets_ref(dpt = DPT_Switch, when = OutputConfigDiscriminant::Switch, function = "Switch state")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Dimmer, function = "Brightness level")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Pwm, function = "PWM level")]
        pub channel_a_out: ComObject<ComObjectStorage<1>>,

        // ====================================================================
        // Channel B: Multi-mode output with ComObjectRefs
        // ====================================================================
        /// Channel B input - receives control commands
        #[ets(
            index = 2,
            display = "Channel B Input",
            function = "Control input",
            selector_param = "channel_b_config_selector"
        )]
        #[ets_ref(dpt = DPT_Switch, when = OutputConfigDiscriminant::Switch, function = "Switch on/off")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Dimmer, function = "Dim value 0-255")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Pwm, function = "PWM value")]
        pub channel_b_in: ComObject<ComObjectStorage<1>>,

        /// Channel B output - sends current state to bus
        #[ets(
            index = 3,
            display = "Channel B Output",
            function = "Status output",
            flags = C | R | W | T | LOW,
            selector_param = "channel_b_config_selector"
        )]
        #[ets_ref(dpt = DPT_Switch, when = OutputConfigDiscriminant::Switch, function = "Switch state")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Dimmer, function = "Brightness level")]
        #[ets_ref(dpt = DPT_Value_1_Ucount, when = OutputConfigDiscriminant::Pwm, function = "PWM level")]
        pub channel_b_out: ComObject<ComObjectStorage<1>>,

        // ====================================================================
        // Fixed-type objects (no ComObjectRefs)
        // ====================================================================
        /// Scene control input - receives scene recall/store commands
        #[ets(index = 4, display = "Scene Control", function = "Scene recall/store (DPT 17.001)")]
        pub scene_control: ComObject<DPT_Value_1_Ucount>,

        /// Lock input - enables/disables output locking
        #[ets(index = 5, display = "Lock", function = "Output lock control")]
        pub lock_in: ComObject<DPT_Switch>,

        /// General status output - always a switch type
        #[ets(index = 6, display = "In Operation", function = "Device in operation status", flags = C | W | T | LOW)]
        pub in_operation: ComObject<DPT_Switch>,

        /// Error status output
        #[ets(index = 7, display = "Error", function = "Error status output", flags = C | W | T | LOW)]
        pub error_status: ComObject<DPT_Switch>,
    }
}

// ============================================================================
// Application Parameters
// ============================================================================

// ----------------------------------------------------------------------------
// Simple enums for use in EtsUnion variants (type-safe, matchable in Rust)
// ----------------------------------------------------------------------------

/// Analog input type selector.
#[derive(Debug, Clone, Copy, PartialEq, Eq, EtsEnum, Serialize, Deserialize, KnownLayout, Immutable, IntoBytes)]
#[repr(u8)]
pub enum AnalogInputType {
    #[ets(display = "0-10V")]
    Voltage0_10V = 0,
    #[ets(display = "4-20mA")]
    Current4_20mA = 1,
}

impl ConstDefault for AnalogInputType {
    const DEFAULT: Self = Self::Voltage0_10V;
}

/// Temperature sensor type selector.
#[derive(Debug, Clone, Copy, PartialEq, Eq, EtsEnum, Serialize, Deserialize, KnownLayout, Immutable, IntoBytes)]
#[repr(u8)]
pub enum SensorType {
    #[ets(display = "PT100")]
    Pt100 = 0,
    #[ets(display = "PT1000")]
    Pt1000 = 1,
    #[ets(display = "NTC 10K")]
    Ntc10K = 2,
}

impl ConstDefault for SensorType {
    const DEFAULT: Self = Self::Pt100;
}

/// Yes/No boolean selector for invert options.
#[derive(Debug, Clone, Copy, PartialEq, Eq, EtsEnum, Serialize, Deserialize, KnownLayout, Immutable, IntoBytes)]
#[repr(u8)]
pub enum YesNo {
    #[ets(display = "No")]
    No = 0,
    #[ets(display = "Yes")]
    Yes = 1,
}

impl ConstDefault for YesNo {
    const DEFAULT: Self = Self::No;
}

impl From<bool> for YesNo {
    fn from(value: bool) -> Self {
        if value { Self::Yes } else { Self::No }
    }
}

impl From<YesNo> for bool {
    fn from(value: YesNo) -> Self {
        matches!(value, YesNo::Yes)
    }
}

// ----------------------------------------------------------------------------
// EtsUnion enums (with data fields)
// ----------------------------------------------------------------------------

/// Demo union for testing ETS union export.
///
/// The `#[ets_union]` macro generates:
/// - `ETS_UNION_INFO`: Union metadata including variant parameters
/// - `ETS_SELECTOR_VARIANTS`: Enum variants for the discriminant/selector
/// - `EtsUnionType` trait implementation
#[ets_union]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum OutputConfig {
    /// Output disabled
    #[ets(default_variant, display = "Disabled")]
    Disabled = 0,

    /// Switch output mode
    #[ets(display = "Switch Mode")]
    Switch {
        /// Invert the switch output
        #[ets(display = "Invert Output", ets_enum)]
        invert: YesNo,
    },

    /// Dimmer output mode
    #[ets(display = "Dimmer Mode")]
    Dimmer {
        /// Minimum dimmer level (0-100%)
        #[ets(display = "Min Level")]
        min_level: u8,
        /// Maximum dimmer level (0-100%)
        #[ets(display = "Max Level")]
        max_level: u8,
    },

    /// PWM output mode
    #[ets(display = "PWM Mode")]
    Pwm {
        /// PWM frequency in Hz
        #[ets(display = "Frequency")]
        frequency: BeU16,
        /// PWM duty cycle (0-100%)
        #[ets(display = "Duty Cycle")]
        duty_cycle: u8,
    },
}

/// Input source configuration union.
///
/// Demonstrates a union with different input types, each with their own parameters.
#[ets_union]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum InputSource {
    /// No input source configured
    #[ets(default_variant, display = "None")]
    None = 0,

    /// Binary input (digital)
    #[ets(display = "Binary Input")]
    Binary {
        /// Debounce time in milliseconds
        #[ets(display = "Debounce Time")]
        debounce_ms: BeU16,
        /// Invert input logic
        #[ets(display = "Invert", ets_enum)]
        invert: YesNo,
    },

    /// Analog input (0-10V or 4-20mA)
    #[ets(display = "Analog Input")]
    Analog {
        /// Input type
        #[ets(display = "Input Type", ets_enum)]
        input_type: AnalogInputType,
        /// Low threshold value
        #[ets(display = "Low Threshold")]
        low_threshold: BeU16,
        /// High threshold value
        #[ets(display = "High Threshold")]
        high_threshold: BeU16,
    },

    /// Temperature sensor input
    #[ets(display = "Temperature Sensor")]
    Temperature {
        /// Sensor type
        #[ets(display = "Sensor Type", ets_enum)]
        sensor_type: SensorType,
        /// Offset calibration in 0.1°C
        #[ets(display = "Offset")]
        offset: i8,
    },
}

/// Scene configuration union.
///
/// Demonstrates a simple union for scene recall/store behavior.
#[ets_union]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub enum SceneConfig {
    /// Scene disabled
    #[ets(default_variant, display = "Disabled")]
    Disabled = 0,

    /// Recall scene on trigger
    #[ets(display = "Recall Only")]
    RecallOnly {
        /// Scene number to recall (1-64)
        #[ets(display = "Scene Number")]
        scene_number: u8,
    },

    /// Store and recall scene
    #[ets(display = "Store & Recall")]
    StoreAndRecall {
        /// Scene number (1-64)
        #[ets(display = "Scene Number")]
        scene_number: u8,
        /// Long press time for store in 100ms units
        #[ets(display = "Store Time")]
        store_time: u8,
    },
}

/// Application parameters for the demo device.
///
/// The `#[ets_params]` macro generates:
/// - `ETS_PARAMS`: Basic parameter definitions
/// - `ETS_PARAMS_EXT`: Extended definitions with enum variants
/// - `MODE_VARIANTS`: Auto-generated const for enum variants (named after the field)
/// - `ETS_UNIONS`: Union field information for union parameters
///
/// ## ComObjectRef Integration
///
/// The `channel_a_config` and `channel_b_config` union parameters control which
/// ComObjectRef is active for each channel. The union selector (e.g. "Switch Mode")
/// determines which variant-specific parameters are shown, AND which comm object
/// DPT is active.
///
/// Union fields can be placed anywhere in the struct. The macro uses `core::mem::offset_of!`
/// to correctly calculate field offsets regardless of union placement.
#[ets_params]
#[derive(Debug, Clone, Copy, Serialize, Deserialize)]
pub struct DemoParams {
    /// Channel A output configuration - controls comm object DPT and mode-specific params
    #[ets(union, display = "Channel A Config")]
    pub channel_a_config: OutputConfig,

    /// Channel B output configuration
    #[ets(union, display = "Channel B Config")]
    pub channel_b_config: OutputConfig,

    /// Input source configuration
    #[ets(union, display = "Input Source")]
    pub input_source: InputSource,

    /// Scene configuration
    #[ets(union, display = "Scene Config")]
    pub scene_config: SceneConfig,

    /// Send cycle time in seconds (0 = disabled)
    #[ets(display = "Send Cycle Time", enum_variants("Disabled" => 0, "10s" => 10, "30s" => 30, "60s" => 60, "300s" => 300))]
    pub send_cycle_time: BeU16,

    /// Lock behavior with enum variants
    #[ets(display = "Lock Behavior", enum_variants("No Action" => 0, "Lock Off" => 1, "Lock On" => 2, "Lock Toggle" => 3))]
    pub lock_behavior: u8,

    /// Gate for the Diagnostics channel tab: the whole tab only exists
    /// while this is "Shown" (a choose directly under Dynamic — the
    /// ETS6 idiom for channels enabled by a parameter).
    #[ets(display = "Diagnostics page", enum_variants("Hidden" => 0, "Shown" => 1))]
    pub show_diagnostics: u8,

    /// Heartbeat supervision interval, shown on the gated Diagnostics tab
    #[ets(display = "Heartbeat Interval", enum_variants("30s" => 0, "60s" => 1, "300s" => 2))]
    pub heartbeat_interval: u8,
}

// ============================================================================
// ETS Page Layout
// ============================================================================

impl EtsPageLayout for SystemBDemoDevice {
    fn page_layout() -> PageStructure {
        use InputSourceDiscriminant::*;
        use OutputConfigDiscriminant::*;
        use SceneConfigDiscriminant::*;

        ets_pages! {
            // Device-wide settings shown at the top level (not in any channel tab)
            device {
                // General device behavior settings
                block "general" => "General" {
                    param send_cycle_time
                    sep "Scene Control"
                    selector scene_config
                    obj scene_control
                    sep "Lock"
                    param lock_behavior
                    obj lock_in
                    sep "Pages"
                    param show_diagnostics
                }

                // Scene-specific settings appear conditionally
                // Using new path syntax: union_field::Variant.field
                when scene_config {
                    [RecallOnly] => {
                        block "scene_recall" => "    Scene Settings" {
                            param scene_config::RecallOnly.scene_number
                        }
                    }
                    [StoreAndRecall] => {
                        block "scene_store" => "    Scene Settings" {
                            param scene_config::StoreAndRecall.scene_number
                            param scene_config::StoreAndRecall.store_time
                        }
                    }
                }

                // Input source configuration
                block "input" => "Input" {
                    selector input_source
                }

                when input_source {
                    [Binary] => {
                        block "input_binary" => "    Binary Input Settings" {
                            param input_source::Binary.debounce_ms
                            param input_source::Binary.invert
                        }
                    }
                    [Analog] => {
                        block "input_analog" => "    Analog Input Settings" {
                            param input_source::Analog.input_type
                            sep "Thresholds"
                            param input_source::Analog.low_threshold
                            param input_source::Analog.high_threshold
                        }
                    }
                    [Temperature] => {
                        block "input_temp" => "    Temperature Sensor Settings" {
                            param input_source::Temperature.sensor_type
                            param input_source::Temperature.offset
                        }
                    }
                }

                // Status outputs (fixed, always visible)
                block "status" => "Status" {
                    obj in_operation
                    obj error_status
                }
            }

            // Outputs channel - groups output comm objects in Group Objects view
            channel "outputs" => "Outputs" (1) {
                // Output channel configuration - mode selectors
                block "output_config" => "Configuration" {
                    selector channel_a_config
                    selector channel_b_config
                }

                // Channel A config blocks appear below based on selection
                // The comm objects are conditional and will auto-wrap in choose/when
                when channel_a_config {
                    [Switch] => {
                        block "channel_a_switch" => "Channel A: Switch" {
                            param channel_a_config::Switch.invert
                            obj channel_a_in
                            obj channel_a_out
                        }
                    }
                    [Dimmer] => {
                        block "channel_a_dimmer" => "Channel A: Dimmer" {
                            param channel_a_config::Dimmer.min_level
                            param channel_a_config::Dimmer.max_level
                            obj channel_a_in
                            obj channel_a_out
                        }
                    }
                    [Pwm] => {
                        block "channel_a_pwm" => "Channel A: PWM" {
                            param channel_a_config::Pwm.frequency
                            param channel_a_config::Pwm.duty_cycle
                            obj channel_a_in
                            obj channel_a_out
                        }
                    }
                }

                // Channel B config blocks appear below based on selection
                when channel_b_config {
                    [Switch] => {
                        block "channel_b_switch" => "Channel B: Switch" {
                            param channel_b_config::Switch.invert
                            obj channel_b_in
                            obj channel_b_out
                        }
                    }
                    [Dimmer] => {
                        block "channel_b_dimmer" => "Channel B: Dimmer" {
                            param channel_b_config::Dimmer.min_level
                            param channel_b_config::Dimmer.max_level
                            obj channel_b_in
                            obj channel_b_out
                        }
                    }
                    [Pwm] => {
                        block "channel_b_pwm" => "Channel B: PWM" {
                            param channel_b_config::Pwm.frequency
                            param channel_b_config::Pwm.duty_cycle
                            obj channel_b_in
                            obj channel_b_out
                        }
                    }
                }
            }

            // A whole channel tab gated on a parameter: lowered to a
            // choose directly under Dynamic with the Channel inside
            // the when branch, the way ETS6 products enable channels.
            when @show_diagnostics {
                [1] => {
                    channel "diagnostics" => "Diagnostics" (2) {
                        block "diag" => "Supervision" {
                            param heartbeat_interval
                        }
                    }
                }
            }
        }
    }
}
