//! IP extension: persistent config, runtime state, and augment.
//!
//! Everything related to KNX/IP extension state lives here:
//!
//! - [`IpExtensionConfig`] — serializable IP configuration
//! - [`IpExtensionState`] — runtime state with interior mutability,
//!   exposing the persisted IP config as inherent methods
//! - [`ExtensionState`] + [`Extension<P>`](crate::bcus::system_b::Extension) impls
//! - [`HasIpExtensionState`] impl — accessor so generic context impls
//!   can reach the persisted IP state through any extension wrapper
//! - [`IpAugment`] — combines config + platform for property dispatch
//!
//! PID 68 (`KNXNETIP_DEVICE_CAPABILITIES`) is stored in `IpExtensionState`
//! and set on boot from [`LinkLayerCapabilities`](crate::layers::LinkLayerCapabilities).
//! The platform (`P: IpPlatform`) is passed at the point of use via
//! [`Extension::create_augment`](crate::bcus::system_b::Extension::create_augment).

mod augment;
mod tunnelling;

pub use augment::IpAugment;
pub use tunnelling::{TunnellingAugment, TunnellingExtension, TunnellingExtensionConfig};

use core::cell::Cell;
use core::net::Ipv4Addr;

use embassy_sync::blocking_mutex::raw::NoopRawMutex;
use embassy_sync::channel::Channel;

use crate::IpPlatform;
use crate::StackDefinition;
// `ExtensionState` here is the derive macro (and trait); it generates the
// `IpExtensionConfig` mirror and the `ExtensionState` impl (with `Default`
// and `on_erase` kept hand-written via `default = manual` / `on_erase = manual`).
use crate::HasSecurityMode;
use crate::bcus::system_b::{Extension, ExtensionState, SystemBDeviceState};
use crate::layers::linklayers::knxip::features::{FeatureSet, TunnelingFeature};
use crate::objects::comm::HasGoSecurityView;
use crate::objects::interface::HasDomainAddress;
use crate::restart::EraseCode;
use crate::{HasIpExtensionState, HasRoutingMulticastRebind, IpConfig, IpPlatformConfig};
use zweidraehte_proto::address::IndividualAddress;

/// Channel buffering pushed routing-multicast-group changes from
/// `IpExtensionState::set_*` to the KNX/IP link-layer runtime.
///
/// Capacity 2 absorbs one queued plus one in-flight; a full channel
/// means `try_send` drops, which is safe: the `Cell` is updated
/// unconditionally so the authoritative state is always current, and
/// any subsequent rebind-triggering write reasserts the target.
pub(crate) type RoutingMulticastRebindChannel = Channel<NoopRawMutex, Ipv4Addr, 2>;

// ============================================================================
// IP Extension Config
// ============================================================================

/// Persisted IP configuration (for KNX/IP devices).
///
/// All IP-specific settings that can be configured via ETS or
/// the IP Parameter Object. Implements [`ExtensionConfig`] so it
/// can be used as the `E` parameter of
/// [`DeviceConfig`](crate::bcus::system_b::DeviceConfig).
///
/// Tunnelling-only state (the additional individual address list)
/// lives on [`TunnellingExtensionConfig`](super::TunnellingExtensionConfig)
/// — paired with this config inside
/// [`IpInterfaceExtension`](super::IpInterfaceExtension) on
/// tunnelling-capable devices.
// `IpExtensionConfig` (the persisted mirror) is generated by
// `#[derive(ExtensionState)]` on `IpExtensionState` below. The struct's
// field set, serde derives, and `ExtensionConfig` impl come from the
// derive; only the non-trivial factory `Default` (DHCP method + standard
// `224.0.23.12` multicast group, which are *not* per-field defaults) and
// the address-decoding helpers stay hand-written here — hence
// `default = manual` on the derive.
impl Default for IpExtensionConfig {
    fn default() -> Self {
        Self {
            friendly_name: [0; 30],
            friendly_name_len: 0,
            configured_ip: [0, 0, 0, 0],
            configured_subnet: [255, 255, 255, 0],
            configured_gateway: [0, 0, 0, 0],
            ip_assignment_method: 0x04, // DHCP
            routing_multicast: [224, 0, 23, 12],
            ttl: 16,
            project_installation_id: 0,
        }
    }
}

impl IpExtensionConfig {
    /// Get the configured IP address as an `Ipv4Addr`.
    pub fn configured_ip_addr(&self) -> Ipv4Addr {
        Ipv4Addr::from(self.configured_ip)
    }

    /// Get the routing multicast address as an `Ipv4Addr`.
    pub fn routing_multicast_addr(&self) -> Ipv4Addr {
        Ipv4Addr::from(self.routing_multicast)
    }
}

// ============================================================================
// IP Assignment Result
// ============================================================================

/// Outcome of the IP assignment procedure
/// ([`IpExtensionState::resolve_ip_assignment()`]).
///
/// Returned so the caller (typically the device boot sequence) can log
/// or react to what happened.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IpAssignmentResult {
    /// Static IP was applied from persisted config.
    StaticApplied,

    /// DHCP is active (was already running as boot default, no change).
    DhcpActive,

    /// Configured static IP was invalid (0.0.0.0 address or subnet),
    /// fell back to DHCP (boot default).
    StaticInvalidFallbackDhcp,

    /// No supported assignment method configured. The raw bitfield value
    /// is included for diagnostics.
    Unsupported(u8),
}

// ============================================================================
// Runtime State
// ============================================================================

/// Runtime state for KNX/IP-specific persistent configuration.
///
/// This struct provides interior-mutable access to all IP parameters
/// that are persisted and configurable via ETS / the IP Parameter Object.
/// It bridges the serializable [`IpExtensionConfig`] and the runtime
/// representation with `Cell`/`RefCell` fields.
///
/// The platform is NOT stored here — current network values (actual IP,
/// MAC, etc.) are queried through [`IpAugment`] which combines this
/// config state with a platform reference at the point of use.
///
/// The const generic `N` is the maximum number of additional individual
/// addresses (tunneling slots). Non-tunneling devices use the default
/// `N = 0`, paying zero storage for addresses they never use.
///
/// `IpExtensionState` implements:
/// - [`ExtensionState`] — persistence (serialize/deserialize/factory reset)
/// - [`HasIpExtensionState`] — accessor returning `&Self` for generic
///   navigation; inherent methods on this type provide the IP config
///   property accessors directly
///
/// The const generic `CAPS` is the PID\_KNXNETIP\_DEVICE\_CAPABILITIES
/// bitfield (PID 68). Set it to
/// [`FeatureSet::KNXNETIP_DEVICE_CAPABILITIES`](crate::layers::linklayers::knxip::features::FeatureSet::KNXNETIP_DEVICE_CAPABILITIES)
/// from your link layer's feature type (e.g.,
/// `{ KnxIpDeviceUdp::KNXNETIP_DEVICE_CAPABILITIES }`). The value is
/// baked into the type at compile time — no runtime setter needed.
///
/// Tunnelling-only state (the additional individual address list)
/// lives on [`TunnellingExtension`](super::TunnellingExtension), composed
/// alongside `IpExtensionState` inside
/// [`IpInterfaceExtension`](super::IpInterfaceExtension) on
/// tunnelling-capable devices.
// `#[derive(ExtensionState)]` generates `IpExtensionConfig` (the persisted
// mirror) and the `from_config`/`to_config` glue from these fields. Two
// kinds of field need help the plain `Cell<T>` → `T` unwrap can't give:
//
// - The runtime representation differs from the wire format: `friendly_name_len`
//   is a `usize` for indexing but persists as a `u8`, and the IP addresses are
//   `Ipv4Addr` at runtime but persist as `[u8; 4]`. `#[config(ty = …, from, to)]`
//   carries the explicit conversions.
// - `rebind_channel` is a live signalling channel, never persisted —
//   `#[runtime_only]` omits it from the config and re-creates it in `from_config`.
//
// `on_erase` resets the multicast group *and* pushes it onto the rebind channel,
// a side-effect the field-mapping can't express, so `on_erase = manual` routes
// to the hand-written `on_erase_manual` below. The factory `Default` is also
// hand-written (`default = manual`) because the defaults are not per-field
// `Default::default()` (DHCP method, standard multicast group, …).
//
// `CAPS` is firmware-compiled (PID 68) and persists nowhere; the derive
// ignores generic params for the config, emitting a non-generic config type
// and carrying `<const CAPS: u16>` only on the `ExtensionState` impl.
#[derive(ExtensionState)]
#[extension_state(config = IpExtensionConfig, on_erase = manual, default = manual)]
pub struct IpExtensionState<const CAPS: u16 = 0> {
    friendly_name: Cell<[u8; 30]>,
    #[config(ty = u8, from = |c: u8| c as usize, to = |s: usize| s as u8)]
    friendly_name_len: Cell<usize>,
    #[config(ty = [u8; 4], from = |c: [u8; 4]| Ipv4Addr::from(c), to = |s: Ipv4Addr| s.octets())]
    configured_ip: Cell<Ipv4Addr>,
    #[config(ty = [u8; 4], from = |c: [u8; 4]| Ipv4Addr::from(c), to = |s: Ipv4Addr| s.octets())]
    configured_subnet: Cell<Ipv4Addr>,
    #[config(ty = [u8; 4], from = |c: [u8; 4]| Ipv4Addr::from(c), to = |s: Ipv4Addr| s.octets())]
    configured_gateway: Cell<Ipv4Addr>,
    ip_assignment_method: Cell<u8>,
    #[config(ty = [u8; 4], from = |c: [u8; 4]| Ipv4Addr::from(c), to = |s: Ipv4Addr| s.octets())]
    routing_multicast: Cell<Ipv4Addr>,
    ttl: Cell<u8>,
    project_installation_id: Cell<u16>,
    /// Pushes target routing-multicast group changes to the KNX/IP
    /// link-layer runtime so it can issue the live IGMP rebind within
    /// the 1 s deadline of 03/02/06 §4.3.5.3.5.1. Receiver is drained
    /// inside `KnxNetIp::run`'s main select loop; if no KNX/IP link
    /// layer is running (degenerate configuration) the channel simply
    /// fills and subsequent `try_send`s drop — harmless, because the
    /// `routing_multicast` Cell is the canonical state.
    #[runtime_only(init = Channel::new())]
    rebind_channel: RoutingMulticastRebindChannel,
}

impl<const CAPS: u16> IpExtensionState<CAPS> {
    /// KNXnet/IP device capabilities bitfield (PID 68).
    ///
    /// Compile-time constant derived from the link layer's
    /// [`FeatureSet`](crate::layers::linklayers::knxip::features::FeatureSet).
    pub const fn knxnetip_device_capabilities(&self) -> u16 {
        CAPS
    }

    // NOTE: persistence goes through the derive-generated
    // `ExtensionState::to_config()`. A hand-written `build_ip_config`
    // duplicate used to live here; it had no callers and was a silent
    // drift hazard, so it was removed rather than kept in sync.

    /// Push the current configured IP/subnet/gateway to the platform.
    ///
    /// This is a low-level helper used internally by
    /// [`resolve_ip_assignment()`](Self::resolve_ip_assignment). Prefer
    /// calling `resolve_ip_assignment()` at boot — it validates the
    /// persisted config and follows the KNX IP assignment procedure
    /// before deciding whether to apply.
    fn apply_current_config(&self, platform: &impl IpPlatformConfig) {
        let config = IpConfig {
            assignment_method: self.ip_assignment_method.get(),
            address: self.configured_ip.get(),
            subnet_mask: self.configured_subnet.get(),
            default_gateway: self.configured_gateway.get(),
        };

        if let Err(_e) = platform.apply_ip_config(&config) {
            #[cfg(feature = "log")]
            log::error!("Failed to apply IP config: {:?}", _e);
            #[cfg(feature = "defmt")]
            defmt::error!("Failed to apply IP config: {}", defmt::Debug2Format(&_e));
        }
    }

    /// Run the KNX IP assignment procedure (KNX spec Core 8.5, Figure 42).
    ///
    /// Examines the persisted `ip_assignment_method` bitfield and applies
    /// the appropriate configuration to the platform. Call this once at
    /// boot after loading persisted state from storage.
    ///
    /// # IP Assignment Method Bitfield
    ///
    /// | Bit | Value | Method               |
    /// |-----|-------|----------------------|
    /// |  0  | 0x01  | Manual (static IP)   |
    /// |  1  | 0x02  | BootP                |
    /// |  2  | 0x04  | DHCP                 |
    /// |  3  | 0x08  | AutoIP (RFC 3927)    |
    ///
    /// # Assignment Procedure
    ///
    /// The full spec procedure includes DHCP timeout detection and AutoIP
    /// fallback. This implementation handles the common cases synchronously:
    ///
    /// 1. **Manual bit set + valid address/subnet** → apply static config.
    /// 2. **Manual bit set + invalid address** → fall back to DHCP.
    /// 3. **DHCP bit set (no Manual)** → DHCP is already the boot default.
    /// 4. **Other** → unsupported, stays on whatever is running.
    ///
    /// The async DHCP timeout → AutoIP fallback path (spec steps 4-5, 8-9)
    /// is not yet implemented. AutoIP requires ARP probing which embassy-net
    /// does not support natively.
    pub fn resolve_ip_assignment(&self, platform: &impl IpPlatformConfig) -> IpAssignmentResult {
        let method = self.ip_assignment_method.get();

        // ====================================================================
        // Manual/static takes priority when its bit is set.
        // ====================================================================
        if method & 0x01 != 0 {
            let addr = self.configured_ip.get();
            let mask = self.configured_subnet.get();

            if addr.is_unspecified() || mask.is_unspecified() {
                // Static config is incomplete. Per the spec, if DHCP is also
                // enabled we try DHCP (already the boot default). Without
                // DHCP the spec says to try AutoIP, but that's not supported
                // yet — so we fall back to DHCP regardless.
                // TODO: AutoIP fallback (spec steps 4-5).
                return IpAssignmentResult::StaticInvalidFallbackDhcp;
            }

            // Valid static config — apply it to the platform.
            self.apply_current_config(platform);
            return IpAssignmentResult::StaticApplied;
        }

        // ====================================================================
        // No Manual bit. DHCP is the boot default — nothing to change.
        // ====================================================================
        if method & 0x04 != 0 {
            return IpAssignmentResult::DhcpActive;
        }

        // TODO: BootP (0x02) — not supported.
        // TODO: AutoIP (0x08) as primary method — needs embassy-net link-local.

        IpAssignmentResult::Unsupported(method)
    }
}

// ============================================================================
// ExtensionState
// ============================================================================

// Plain KNX/IP has no Data Secure layer at this level — security on IP
// stacks is added by wrapping `IpExtensionState` in `SecureExtensionState`.
// The bare extension's `Plain` defaults are correct.
impl<const CAPS: u16> HasGoSecurityView for IpExtensionState<CAPS> {}

// The `ExtensionState` impl (Config / Resources / from_config / to_config) is
// generated by `#[derive(ExtensionState)]` on the struct above. `from_config`
// deliberately does *not* call `apply_current_config()`: the caller applies
// the IP config to the platform at the appropriate time — typically only when
// the assignment method is Manual/static. Applying during `from_config` would
// overwrite a DHCP lease acquired before state was loaded from flash (common
// on embedded platforms where DHCP runs during hardware init, before persisted
// state is deserialised). The derive's generated `from_config` only restores
// field values, matching that contract.
//
// `on_erase` is hand-written here (`on_erase = manual` on the derive routes the
// trait method to this `on_erase_manual`) because a factory reset must also
// rebind to the default multicast group via the same channel writes use —
// a side-effect outside the field-mapping.
impl<const CAPS: u16> IpExtensionState<CAPS> {
    fn on_erase_manual(&self, code: EraseCode) {
        if matches!(code, EraseCode::FactoryReset | EraseCode::FactoryResetKeepIA) {
            let defaults: IpExtensionConfig = IpExtensionConfig::default();
            self.friendly_name.set(defaults.friendly_name);
            self.friendly_name_len.set(defaults.friendly_name_len as usize);
            self.configured_ip.set(Ipv4Addr::from(defaults.configured_ip));
            self.configured_subnet.set(Ipv4Addr::from(defaults.configured_subnet));
            self.configured_gateway.set(Ipv4Addr::from(defaults.configured_gateway));
            self.ip_assignment_method.set(defaults.ip_assignment_method);
            let default_mcast = Ipv4Addr::from(defaults.routing_multicast);
            self.routing_multicast.set(default_mcast);
            // Factory reset must also rebind to the default group, via
            // the same path writes use.
            let _ = self.rebind_channel.try_send(default_mcast);
            self.ttl.set(defaults.ttl);
            self.project_installation_id.set(defaults.project_installation_id);
        }
    }
}

impl<const CAPS: u16> HasSecurityMode for IpExtensionState<CAPS> {}

impl<const CAPS: u16> HasRoutingMulticastRebind for IpExtensionState<CAPS> {
    fn routing_multicast_rebind_channel(&self) -> &RoutingMulticastRebindChannel {
        &self.rebind_channel
    }
}

/// `IpExtensionState` alone carries no tunnelling-address storage, so it
/// adopts the trait's no-op defaults. `IpInterfaceExtension` bundles
/// this with a [`TunnellingExtension`] and overrides them.
impl<const CAPS: u16> crate::ip::HasAdditionalIas for IpExtensionState<CAPS> {}

// ============================================================================
// Extension — unified persistence + augmentation
// ============================================================================

impl<P: IpPlatform, const CAPS: u16> Extension<P> for IpExtensionState<CAPS> {
    type Augment<'a, D: StackDefinition>
        = IpAugment<'a, P, CAPS>
    where
        Self: 'a,
        P: 'a;

    fn create_augment<'a, D: StackDefinition>(&'a self, platform: &'a P) -> Self::Augment<'a, D>
    where
        P: 'a,
    {
        IpAugment::new(self, platform)
    }
}

// ============================================================================
// IP Device State Type Alias
// ============================================================================

/// Type alias for KNX/IP device state.
///
/// This is [`SystemBDeviceState`] specialized with [`IpExtensionState`]
/// as the extension state for KNX/IP devices.
///
/// # Generic Parameters
///
/// - `ADT_SIZE`, `AST_SIZE`, `COT_SIZE`: Table sizes (see [`SystemBDeviceState`])
/// - `P`: Application parameters type
/// - `CAPS`: KNXnet/IP device capabilities bitfield (PID 68). Set to
///   `{ YourFeatureSet::KNXNETIP_DEVICE_CAPABILITIES }`.
pub type IpSystemBDeviceState<
    const ADT_SIZE: usize,
    const AST_SIZE: usize,
    const COT_SIZE: usize,
    D,
    const CAPS: u16 = 0,
> = SystemBDeviceState<ADT_SIZE, AST_SIZE, COT_SIZE, D, IpExtensionState<CAPS>>;

/// [`IpExtensionState`] with `CAPS` derived from a
/// [`FeatureSet`](crate::layers::linklayers::knxip::features::FeatureSet).
///
/// Device capabilities are inferred from `F`, so the user passes the
/// same feature type used for the link layer builder:
///
/// ```rust,ignore
/// type ES = IpExtensionFor<KnxIpDeviceUdp>;            // routing-only
/// type ES = IpInterfaceExtensionFor<KnxIpInterfaceUdp<4>>; // tunnelling
/// ```
///
/// Tunnelling-capable devices use [`IpInterfaceExtensionFor`] instead
/// — this typedef carries no tunnelling slot count.
pub type IpExtensionFor<F: FeatureSet> = IpExtensionState<{ <F as FeatureSet>::KNXNETIP_DEVICE_CAPABILITIES }>;

/// [`IpAugment`] with `CAPS` derived from a
/// [`FeatureSet`](crate::layers::linklayers::knxip::features::FeatureSet).
///
/// Use this when spelling out the augment type for devices with extra
/// augments (where `SystemBInterfaceObjectsFor` can't be used):
///
/// ```rust,ignore
/// type InterfaceObjects<'a> = DefaultSystemBInterfaceObjects<
///     'a, MyState, (IpAugmentFor<'a, MyPlatform, KnxIpDeviceUdp>, EasterEggAugment),
/// >;
/// ```
pub type IpAugmentFor<'a, P, F: FeatureSet> = IpAugment<'a, P, { <F as FeatureSet>::KNXNETIP_DEVICE_CAPABILITIES }>;

/// Like [`IpSystemBDeviceState`], but derives `N` and `CAPS` from a
/// [`FeatureSet`](crate::layers::linklayers::knxip::features::FeatureSet).
///
/// ```rust,ignore
/// type MyState = IpDeviceState<ADT, AST, COT, MyParams, KnxIpDeviceTcp>;
/// ```
pub type IpDeviceState<
    const ADT_SIZE: usize,
    const AST_SIZE: usize,
    const COT_SIZE: usize,
    D: StackDefinition,
    F: FeatureSet,
> = SystemBDeviceState<ADT_SIZE, AST_SIZE, COT_SIZE, D, IpExtensionFor<F>>;

// ============================================================================
// IpInterfaceExtension — IP + tunnelling aggregator
// ============================================================================

/// IP extension aggregator for tunnelling-capable devices.
///
/// Pairs an [`IpExtensionState`] (with `N = 0` because the inner
/// extension carries no tunnelling slots in this composition) with a
/// [`TunnellingExtension`] sized at `N`. The aggregator implements
/// every trait the device's `D::State` flow expects from a single
/// extension — `ExtensionState`, `Extension<P>`, `HasIpExtensionState`,
/// `HasAdditionalIas`, `HasGoSecurityView`, `HasSecurityMode`,
/// `HasRoutingMulticastRebind`, `HasDomainAddress` — by delegating
/// each to the inner part that owns the relevant state.
///
/// The augment side is the
/// [`#[derive(ServiceRegistry)]`](crate::service::ServiceRegistry)
/// bundle [`IpInterfaceAugmentBundle`], which chains
/// [`TunnellingAugment`] before [`IpAugment`] so that PIDs 53 and 79
/// land on the new dispatch path; PIDs the inner `IpAugment` owns
/// (the routing-only IP PIDs) fall through to it.
///
/// `Config` round-trips as a `(IpExtensionConfig,
/// TunnellingExtensionConfig<N>)` tuple — flash payloads grown in
/// previous releases are migrated by the device's storage layer when
/// it picks up this struct as the new `ES`.
pub struct IpInterfaceExtension<const N: usize, const CAPS: u16> {
    /// IP-side state.
    pub ip: IpExtensionState<CAPS>,
    /// Tunnelling-side state (`N` slots).
    pub tunnelling: TunnellingExtension<N>,
}

// Forward both security-view traits explicitly to `self.ip` rather than relying
// on the default no-op bodies. If `IpExtensionState` ever implements these
// traits non-trivially (e.g., when a secure IP extension gains its own
// security-mode flag), the aggregator would silently diverge from the inner
// state if the forwarding were implicit. Making it explicit prevents that.
forward_to_field! {
    impl<[const N: usize, const CAPS: u16]> HasGoSecurityView for IpInterfaceExtension<N, CAPS> {
        get fn required_security_for_asap(&self, asap: u16) -> zweidraehte_proto::messages::knx::RequiredSecurity;
        get fn required_security_for_p2p(&self, peer_ia: u16) -> zweidraehte_proto::messages::knx::RequiredSecurity;
        get fn required_security_for_broadcast(&self) -> zweidraehte_proto::messages::knx::RequiredSecurity;
        get fn required_security_for_tool_access(&self) -> zweidraehte_proto::messages::knx::RequiredSecurity;
    } => self.ip
}

forward_to_field! {
    impl<[const N: usize, const CAPS: u16]> HasSecurityMode for IpInterfaceExtension<N, CAPS> {
        get fn security_mode_enabled(&self) -> bool;
        out fn log_access_denied(&self, source_addr: u16);
        get fn has_group_key(&self, tsap: u16) -> bool;
    } => self.ip
}

impl<const N: usize, const CAPS: u16> HasRoutingMulticastRebind for IpInterfaceExtension<N, CAPS> {
    fn routing_multicast_rebind_channel(&self) -> &RoutingMulticastRebindChannel {
        self.ip.routing_multicast_rebind_channel()
    }
}

impl<const N: usize, const CAPS: u16> ExtensionState for IpInterfaceExtension<N, CAPS> {
    type Config = (IpExtensionConfig, TunnellingExtensionConfig<N>);
    type Resources = ();

    fn from_config((ip_cfg, tun_cfg): Self::Config, _resources: ()) -> Self {
        Self {
            ip: IpExtensionState::<CAPS>::from_config(ip_cfg, ()),
            tunnelling: TunnellingExtension::<N>::from_config(tun_cfg, ()),
        }
    }

    fn to_config(&self) -> Self::Config {
        (self.ip.to_config(), self.tunnelling.to_config())
    }

    fn on_erase(&self, code: EraseCode) {
        self.ip.on_erase(code);
        self.tunnelling.on_erase(code);
    }
}

/// `HasIpExtensionState` lets generic code reach the persisted IP
/// state through the wrapper. Tunnelling-side state lives in the
/// paired [`TunnellingExtension`] and is exposed separately via
/// [`HasAdditionalIas`](crate::ip::HasAdditionalIas).
impl<const N: usize, const CAPS: u16> HasIpExtensionState for IpInterfaceExtension<N, CAPS> {
    fn ip_state(&self) -> &dyn crate::ip::IpStateView {
        &self.ip
    }
}

impl<const N: usize, const CAPS: u16> crate::ip::HasAdditionalIas for IpInterfaceExtension<N, CAPS> {
    fn write_additional_ias_into(&self, buf: &mut [IndividualAddress]) -> usize {
        self.tunnelling.write_into(buf)
    }

    fn additional_ia_is_assigned(&self, addr: IndividualAddress) -> bool {
        self.tunnelling.contains(addr)
    }
}

impl<const N: usize, const CAPS: u16> HasDomainAddress for IpInterfaceExtension<N, CAPS> {
    const DOMAIN_ADDRESS_LENGTH: usize = IpExtensionState::<CAPS>::DOMAIN_ADDRESS_LENGTH;

    fn domain_address(&self, buf: &mut [u8]) {
        self.ip.domain_address(buf);
    }

    fn set_domain_address(&self, addr: &[u8]) {
        self.ip.set_domain_address(addr);
    }
}

/// `Augment<D>` bundle for [`IpInterfaceExtension`].
///
/// Both peer augments target the IP Parameter Object (Type 11) but
/// own disjoint PIDs — `TunnellingAugment` claims 53 and 79,
/// `IpAugment` owns the rest — so the chain order doesn't affect
/// correctness. `TunnellingAugment` is listed first so its
/// const-generic-`N` descriptor lookup runs before any future IP-side
/// addition for the same PID space.
#[derive(crate::service::ServiceRegistry)]
pub struct IpInterfaceAugmentBundle<'a, P: IpPlatform, const N: usize, const CAPS: u16> {
    #[service(augment)]
    pub tunnelling: TunnellingAugment<'a, N>,
    #[service(augment)]
    pub ip: IpAugment<'a, P, CAPS>,
}

impl<P: IpPlatform, const N: usize, const CAPS: u16> Extension<P> for IpInterfaceExtension<N, CAPS> {
    type Augment<'a, D: StackDefinition>
        = IpInterfaceAugmentBundle<'a, P, N, CAPS>
    where
        Self: 'a,
        P: 'a;

    fn create_augment<'a, D: StackDefinition>(&'a self, platform: &'a P) -> Self::Augment<'a, D>
    where
        P: 'a,
    {
        IpInterfaceAugmentBundle {
            tunnelling: self.tunnelling.create_augment::<D>(&()),
            ip: self.ip.create_augment::<D>(platform),
        }
    }
}

/// [`IpInterfaceExtension`] with `N` and `CAPS` derived from a
/// [`FeatureSet`](crate::layers::linklayers::knxip::features::FeatureSet).
///
/// Mirror of [`IpExtensionFor`] for tunnelling-capable devices.
///
/// ```rust,ignore
/// type ES = IpInterfaceExtensionFor<KnxIpInterfaceUdp<4>>;
/// ```
pub type IpInterfaceExtensionFor<F: FeatureSet> = IpInterfaceExtension<
    { <<F as FeatureSet>::Tunneling as TunnelingFeature>::CAPACITY },
    { <F as FeatureSet>::KNXNETIP_DEVICE_CAPABILITIES },
>;

/// Like [`IpDeviceState`], but uses [`IpInterfaceExtension`] as the
/// extension state — pairs an `IpExtensionState` with a
/// `TunnellingExtension`.
pub type IpInterfaceDeviceState<
    const ADT_SIZE: usize,
    const AST_SIZE: usize,
    const COT_SIZE: usize,
    D: StackDefinition,
    F: FeatureSet,
> = SystemBDeviceState<ADT_SIZE, AST_SIZE, COT_SIZE, D, IpInterfaceExtensionFor<F>>;

// ============================================================================
// IpStateView — persisted config accessors (single canonical impl)
// ============================================================================

impl<const CAPS: u16> crate::ip::IpStateView for IpExtensionState<CAPS> {
    fn configured_ip_address(&self) -> Ipv4Addr {
        self.configured_ip.get()
    }

    fn set_configured_ip_address(&self, addr: Ipv4Addr) {
        self.configured_ip.set(addr);
    }

    fn configured_subnet_mask(&self) -> Ipv4Addr {
        self.configured_subnet.get()
    }

    fn set_configured_subnet_mask(&self, mask: Ipv4Addr) {
        self.configured_subnet.set(mask);
    }

    fn configured_default_gateway(&self) -> Ipv4Addr {
        self.configured_gateway.get()
    }

    fn set_configured_default_gateway(&self, gateway: Ipv4Addr) {
        self.configured_gateway.set(gateway);
    }

    fn ip_assignment_method(&self) -> u8 {
        self.ip_assignment_method.get()
    }

    fn set_ip_assignment_method(&self, method: u8) {
        self.ip_assignment_method.set(method);
    }

    fn routing_multicast_address(&self) -> Ipv4Addr {
        self.routing_multicast.get()
    }

    fn set_routing_multicast_address(&self, addr: Ipv4Addr) {
        self.routing_multicast.set(addr);
        // Notify the KNX/IP link-layer runtime so it can rejoin the
        // multicast group in time for MaC's 1 s retry window
        // (03/02/06 §4.3.5.3.5.1). Drop on a full channel is fine —
        // the Cell above is the authoritative value.
        let _ = self.rebind_channel.try_send(addr);
    }

    fn ttl(&self) -> u8 {
        self.ttl.get()
    }

    fn set_ttl(&self, ttl: u8) {
        self.ttl.set(ttl);
    }

    fn friendly_name_len(&self) -> usize {
        self.friendly_name_len.get()
    }

    fn friendly_name(&self) -> [u8; 30] {
        self.friendly_name.get()
    }

    fn set_friendly_name(&self, name: &[u8]) {
        let mut fname = [0u8; 30];
        let len = name.len().min(30);
        fname[..len].copy_from_slice(&name[..len]);
        self.friendly_name.set(fname);
        self.friendly_name_len.set(len);
    }

    fn project_installation_id(&self) -> u16 {
        self.project_installation_id.get()
    }

    fn set_project_installation_id(&self, id: u16) {
        self.project_installation_id.set(id);
    }
}

impl<const CAPS: u16> HasIpExtensionState for IpExtensionState<CAPS> {
    fn ip_state(&self) -> &dyn crate::ip::IpStateView {
        self
    }
}

// ============================================================================
// HasDomainAddress — IP domain address is the routing multicast address
// ============================================================================

impl<const CAPS: u16> HasDomainAddress for IpExtensionState<CAPS> {
    /// KNX/IP domain address is 4 bytes (IPv4 routing multicast address).
    ///
    /// Per the KNX IP Communication Medium spec (03_02_06, section
    /// 4.3.5.3.4), `A_DomainAddressSerialNumber_Write` carries a 4-octet
    /// domain address which is the routing multicast address
    /// (PID_ROUTING_MULTICAST_ADDRESS).
    const DOMAIN_ADDRESS_LENGTH: usize = 4;

    fn domain_address(&self, buf: &mut [u8]) {
        buf[..4].copy_from_slice(&self.routing_multicast.get().octets());
    }

    fn set_domain_address(&self, addr: &[u8]) {
        let octets: [u8; 4] = addr[..4].try_into().expect("domain address must be 4 bytes for IP");
        let ip = Ipv4Addr::from(octets);
        self.routing_multicast.set(ip);
        // `A_DomainAddressSerialNumber_Write` is the other trigger for
        // the 1 s rebind window; funnel it through the same channel as
        // the PID write path so the runtime handles both identically.
        let _ = self.rebind_channel.try_send(ip);
    }
}
