//! Stack definition for the Linux-hosted light switch.
//!
//! Binds the transport-agnostic [`devices::light_switch`] definition to this
//! target's transport and platform: KNX/IP over the Linux socket stack, with
//! the read-only [`LinuxIpPlatform`] reporting the host's actual network
//! configuration (the OS owns networking, so `apply_ip_config` is a no-op).
//!
//! This is the host-target sibling of `firmware/rp2040/eth_light_switch`: same
//! device definition and feature set (`KnxIpDeviceTcp` — routing + remote
//! config + TCP, no tunnelling), just over `LinuxIpTransport` instead of
//! embassy-net on a W5500.

use devices::light_switch::{
    DEVICE_DESCRIPTOR_IP, LightSwitchParams, comm_objs::LightSwitchComObjects, easter_egg::EasterEggAugment,
};
use zweidraehte_device::bcus::system_b::{Extension, IpAugmentFor, IpExtensionFor, IpStateFor};
use zweidraehte_device::layers::linklayers::knxip::{KnxNetIpBuilder, KnxNetIpDefinition, features::KnxIpDeviceTcp};
use zweidraehte_device::layers::transport::TlStyle;
use zweidraehte_device::prelude::*;
use zweidraehte_platform::{LinuxIpPlatform, LinuxIpTransport};

/// Unified state type. Table sizes derive from `DEVICE_DESCRIPTOR_IP`
/// through the `SystemBStackDefinition` associated consts.
pub type LightSwitchState = IpStateFor<LinuxEthLightSwitch, KnxIpDeviceTcp>;

#[derive(Debug, Clone, Copy)]
pub struct LinuxEthLightSwitch;

/// Augment chain: the IP medium augment (KNXnet/IP Parameter object) plus the
/// Easter Egg demo augment, matching the RP2040 light switch.
#[derive(zweidraehte_device::service::ServiceRegistry)]
pub struct LightSwitchAugments<'a> {
    #[service(augment)]
    ip: IpAugmentFor<'a, LinuxIpPlatform, KnxIpDeviceTcp>,
    #[service(augment)]
    easter: EasterEggAugment,
}

// IP-specific link-layer bill of materials. `KnxIpDeviceTcp` is a routing
// device with no tunnelling, so `TUNNEL_CAPACITY = 0` and the derived TCP
// stream/channel defaults collapse to 0. `MAX_UDP_SOCKETS` stays at the trait
// default of 2 (discovery + routing share one multicast socket; unicast
// control wants the second).
impl KnxNetIpDefinition for LinuxEthLightSwitch {
    type Transport = LinuxIpTransport;
    type Features = KnxIpDeviceTcp;
}

// The always-identical System B stack shell (StateInit/Mem, create_state, the
// InterfaceObjects/Augments GATs and the two `create_*` bodies, plus the empty
// `SystemBStackDefinition` impl) is generated by `system_b_standard_stack!`;
// only the device-specific bill of materials is spelled out here.
zweidraehte_device::system_b_standard_stack! {
    stack: LinuxEthLightSwitch,
    device: &DEVICE_DESCRIPTOR_IP,
    tl_style: TlStyle::Style1,
    params: LightSwitchParams,
    com_objects: LightSwitchComObjects,
    link_layer_builder: KnxNetIpBuilder<LinuxEthLightSwitch>,
    platform: LinuxIpPlatform,
    extension_state: IpExtensionFor<KnxIpDeviceTcp>,
    state: LightSwitchState,
    al_extensions: (
        zweidraehte_device::layers::application::services::SystemBAlServices,
        zweidraehte_device::layers::application::services::DomainAddressService,
    ),
    layer_builder: InsecureIpDeviceBuilder,
    augments: {
        bundle: LightSwitchAugments,
        create: |state, platform, _layer_ctx| LightSwitchAugments {
            ip: state.extension_state().create_augment::<Self>(platform),
            easter: EasterEggAugment,
        },
    },
}
