//! Stack definition for the Linux-hosted light switch.
//!
//! Binds the transport-agnostic [`devices::light_switch`] definition to this
//! target's transport and platform: KNX/IP over the Linux socket stack, with
//! the read-only [`LinuxIpPlatform`] reporting the host's actual network
//! configuration (the OS owns networking, so `apply_ip_config` is a no-op).
//!
//! This is the host-target sibling of `firmware/rp2040/eth_light_switch`: the
//! same device definition, but a different feature set. The RP2040 target is
//! UDP-only (`KnxIpDeviceUdp`) because its embassy-net TCP is still a stub;
//! this host target runs `KnxIpDeviceTcp` (routing + remote config + TCP, no
//! tunnelling) over `LinuxIpTransport`, whose TCP listener/stream are a real
//! `std::net` implementation.

use devices::light_switch::{
    DEVICE_DESCRIPTOR_IP, LightSwitchParams, comm_objs::LightSwitchComObjects, easter_egg::EasterEggAugment,
};
use zweidraehte_device::bcus::system_b::{Extension, IpAugmentFor, IpExtensionFor, IpStateFor};
use zweidraehte_device::layers::application::services::{DomainAddressService, StandardAlServices};
use zweidraehte_device::layers::linklayers::knxip::{KnxNetIpBuilder, KnxNetIpDefinition, features::KnxIpDeviceTcp};
use zweidraehte_device::layers::transport::TlStyle;
use zweidraehte_device::prelude::*;
use zweidraehte_device::service::ServiceRegistry;
use zweidraehte_device::storage::ConfigStorage;
use zweidraehte_platform::{LinuxIpPlatform, LinuxIpTransport};

use support::storage::{FileIdentity, JsonStorage};

/// Unified state type. Table sizes derive from `DEVICE_DESCRIPTOR_IP`
/// through the `SystemBStackDefinition` associated consts.
pub type LightSwitchState = IpStateFor<LinuxEthLightSwitch, KnxIpDeviceTcp>;

/// On-stack config store: the JSON-file config backend wrapped in the
/// framework's [`ConfigStorage`] composite. Riding on the stack (rather than
/// living in `main`) lets this device use the shared `storage_task` for restart
/// handling and persistence, exactly like the embedded targets.
pub type LightSwitchStorage = ConfigStorage<JsonStorage<LightSwitchState, FileIdentity>>;

#[derive(Debug, Clone, Copy)]
pub struct LinuxEthLightSwitch;

/// Augment chain: the IP medium augment (KNXnet/IP Parameter object) plus the
/// Easter Egg demo augment, matching the RP2040 light switch.
#[derive(ServiceRegistry)]
pub struct LightSwitchAugments<'a> {
    #[service(augment)]
    ip: IpAugmentFor<'a, LinuxIpPlatform, KnxIpDeviceTcp>,
    #[service(augment)]
    easter: EasterEggAugment,
}

// IP-specific link-layer bill of materials. `KnxIpDeviceTcp` is a routing
// device with no tunnelling, so `TUNNEL_CAPACITY = 0`. Because TCP is enabled,
// the derived `MAX_TCP_STREAMS` / `MAX_TCP_CHANNELS` defaults are `1` — the one
// TCP connection every TCP-capable server must accept (03/08/02 Core §6.5),
// carrying the Device Management connection ETS opens over TCP. `MAX_UDP_SOCKETS`
// stays at the trait default of 2 (discovery + routing share one multicast
// socket; unicast control wants the second).
impl KnxNetIpDefinition for LinuxEthLightSwitch {
    type Transport = LinuxIpTransport;
    type Features = KnxIpDeviceTcp;
}

// The always-identical System B stack shell (StateInit/Mem, create_state, the
// InterfaceObjects/Augments GATs and the two `create_*` bodies, plus the empty
// `SystemBStackDefinition` impl) is generated by `system_b_standard_stack!`;
// only the device-specific bill of materials is spelled out here.
zweidraehte_device::system_b_standard_stack! {
    stack: LinuxEthLightSwitch,
    device: &DEVICE_DESCRIPTOR_IP,
    tl_style: TlStyle::Style3,
    params: LightSwitchParams,
    com_objects: LightSwitchComObjects,
    link_layer_builder: KnxNetIpBuilder<LinuxEthLightSwitch>,
    platform: LinuxIpPlatform,
    extension_state: IpExtensionFor<KnxIpDeviceTcp>,
    state: LightSwitchState,
    al_extensions: (
        StandardAlServices,
        DomainAddressService,
    ),
    layer_builder: PlainIpDeviceBuilder,
    augments: {
        bundle: LightSwitchAugments,
        create: |state, platform, _layer_ctx| LightSwitchAugments {
            ip: state.extension_state().create_augment::<Self>(platform),
            easter: EasterEggAugment,
        },
    },
    extra {
        // The JSON-file config store rides on the stack so the shared
        // `storage_task` can pull it through `HasConfigStore` — restart
        // handling and persistence go through one task, as on the embedded
        // devices, instead of a hand-rolled restart handler in `main`.
        type Storage = &'static LightSwitchStorage;
    },
}
