//! Focused project rendering used by non-interactive skeleton generation and
//! product-only editors. Existing projects are changed by replacing one
//! device declaration and inserting only newly referenced nets; unrelated
//! source, comments, and formatting remain byte-for-byte intact.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use thiserror::Error;
use zweidraehte_proto::address::{GroupAddress, IndividualAddress};

use crate::{
    AuthoredProject, MembershipRole, NetId, NetSecurityPolicy, ObjectFlagOverrides, ObjectPriority, ParamValue,
    ParameterAssignment, ProjectDeviceId, ProjectObjectConfiguration,
};

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DraftNet {
    pub id: NetId,
    pub address: GroupAddress,
    pub dpt: String,
    pub security: NetSecurityPolicy,
}

#[derive(Debug, Clone, PartialEq)]
pub struct ProjectDeviceDraft {
    pub id: ProjectDeviceId,
    pub product: PathBuf,
    pub address: IndividualAddress,
    pub serial: Option<[u8; 6]>,
    pub max_apdu: Option<u16>,
    pub parameters: Vec<ParameterAssignment>,
    pub objects: BTreeMap<u16, ProjectObjectConfiguration>,
    pub nets: BTreeMap<NetId, DraftNet>,
}

#[derive(Debug, Error)]
pub enum RenderError {
    #[error("the project has no device `{0}`")]
    UnknownDevice(ProjectDeviceId),
    #[error("device `{device}` cannot move outside its enclosing area/line through a local edit")]
    TopologyMove { device: ProjectDeviceId },
    #[error("net identifier `{0}` conflicts with an existing net")]
    NetConflict(NetId),
    #[error("product path {0} is not relative to project.knx")]
    AbsoluteProduct(PathBuf),
}

/// Render a complete minimal one-device project.
pub fn render_single_device_project(draft: &ProjectDeviceDraft) -> Result<String, RenderError> {
    if draft.product.is_absolute() {
        return Err(RenderError::AbsoluteProduct(draft.product.clone()));
    }
    let mut output = String::from("# KNX project generated by zweidraehte\n\n");
    render_nets(&mut output, draft.nets.values());
    writeln!(output, "area {} project {{", draft.address.area()).expect("String writes cannot fail");
    writeln!(output, "    line {} main {{", draft.address.line()).expect("String writes cannot fail");
    writeln!(output, "        medium tp1\n").expect("String writes cannot fail");
    output.push_str(&render_device(draft, 8));
    output.push_str("    }\n}\n");
    Ok(output)
}

impl AuthoredProject {
    /// Return source with one device configuration replaced and newly used
    /// nets inserted before the first area. No file is written here.
    pub fn render_device_update(&self, draft: &ProjectDeviceDraft) -> Result<String, RenderError> {
        let current = self.devices.get(&draft.id).ok_or_else(|| RenderError::UnknownDevice(draft.id.clone()))?;
        if current.area != draft.address.area() || current.line != draft.address.line() {
            return Err(RenderError::TopologyMove { device: draft.id.clone() });
        }
        if draft.product.is_absolute() {
            return Err(RenderError::AbsoluteProduct(draft.product.clone()));
        }
        for (id, net) in &draft.nets {
            if let Some(existing) = self.nets.get(id)
                && (existing.address != net.address || existing.dpt != net.dpt)
            {
                return Err(RenderError::NetConflict(id.clone()));
            }
        }

        // Locate the enclosing top-level declarations before replacing the
        // device. Device spans refer to the authored source, while rendering a
        // changed device may alter every byte offset after its start.
        let first_device = self.devices.values().map(|device| device.span.start).min().unwrap_or(self.source.len());
        let area_start = self.source[..first_device].rfind("area ").unwrap_or(first_device);

        let rendered_device = render_device(draft, 8);
        let mut replacements = vec![(current.span, rendered_device.trim_end().to_string())];
        for (id, net) in &draft.nets {
            if let Some(existing) = self.nets.get(id)
                && existing.security != net.security
            {
                replacements.push((existing.security_span, policy_name(net.security).to_string()));
            }
        }
        let area_shift: isize = replacements
            .iter()
            .filter(|(span, _)| span.end <= area_start)
            .map(|(span, replacement)| replacement.len() as isize - (span.end - span.start) as isize)
            .sum();
        replacements.sort_by_key(|(span, _)| std::cmp::Reverse(span.start));
        let mut source = self.source.clone();
        for (span, replacement) in replacements {
            source.replace_range(span.start..span.end, &replacement);
        }
        let new_ids: BTreeSet<_> = draft.nets.keys().filter(|id| !self.nets.contains_key(*id)).cloned().collect();
        if !new_ids.is_empty() {
            let mut added = String::new();
            render_nets(&mut added, new_ids.iter().map(|id| &draft.nets[id]));
            let adjusted_area = usize::try_from(area_start as isize + area_shift).expect("area remains in source");
            source.insert_str(adjusted_area, &added);
        }
        Ok(source)
    }
}

fn render_nets<'a>(output: &mut String, nets: impl IntoIterator<Item = &'a DraftNet>) {
    let nets: Vec<_> = nets.into_iter().collect();
    for net in &nets {
        writeln!(output, "ga {} = {}", net.id, net.address).expect("String writes cannot fail");
    }
    if !nets.is_empty() {
        output.push('\n');
    }
    for net in &nets {
        writeln!(output, "net {} : {} {{ security {} }}", net.id, net.dpt, policy_name(net.security))
            .expect("String writes cannot fail");
    }
    if !nets.is_empty() {
        output.push('\n');
    }
}

fn render_device(draft: &ProjectDeviceDraft, indent: usize) -> String {
    let prefix = " ".repeat(indent);
    let nested = " ".repeat(indent + 4);
    let mut output = String::new();
    writeln!(output, "{prefix}device {} {{", draft.id).expect("String writes cannot fail");
    writeln!(output, "{nested}product local:{}", quote_path(&draft.product)).expect("String writes cannot fail");
    writeln!(output, "{nested}address {}", draft.address).expect("String writes cannot fail");
    if let Some(serial) = draft.serial {
        writeln!(output, "{nested}serial \"{}\"", crate::format_serial(&serial)).expect("String writes cannot fail");
    }
    if let Some(max_apdu) = draft.max_apdu {
        writeln!(output, "{nested}max_apdu {max_apdu}").expect("String writes cannot fail");
    }
    for parameter in &draft.parameters {
        writeln!(output, "{nested}param {} = {}", quote(&parameter.id), render_value(&parameter.value))
            .expect("String writes cannot fail");
    }
    for object in draft.objects.values() {
        writeln!(output, "\n{nested}object {} {{", object.com_object).expect("String writes cannot fail");
        for membership in &object.memberships {
            let keyword = if membership.role == MembershipRole::Primary { "on" } else { "also on" };
            writeln!(output, "{nested}    {keyword} {}", membership.net).expect("String writes cannot fail");
        }
        if object.flags != ObjectFlagOverrides::default() {
            writeln!(output, "\n{nested}    flags {{").expect("String writes cannot fail");
            render_flags(&mut output, &nested, object.flags);
            writeln!(output, "{nested}    }}").expect("String writes cannot fail");
        }
        writeln!(output, "{nested}}}").expect("String writes cannot fail");
    }
    writeln!(output, "{prefix}}}").expect("String writes cannot fail");
    output
}

fn render_flags(output: &mut String, prefix: &str, flags: ObjectFlagOverrides) {
    let entries = [
        ("communication", flags.communication),
        ("read", flags.read),
        ("write", flags.write),
        ("transmit", flags.transmit),
        ("update", flags.update),
        ("read_on_init", flags.read_on_init),
    ];
    for (name, value) in entries {
        if let Some(value) = value {
            writeln!(output, "{prefix}        {name} {value}").expect("String writes cannot fail");
        }
    }
    if let Some(priority) = flags.priority {
        writeln!(output, "{prefix}        priority {}", priority_name(priority)).expect("String writes cannot fail");
    }
}

fn quote_path(path: &Path) -> String {
    quote(&path.to_string_lossy())
}

fn quote(value: &str) -> String {
    format!("\"{}\"", value.replace('\\', "\\\\").replace('"', "\\\""))
}

fn render_value(value: &ParamValue) -> String {
    match value {
        ParamValue::Integer(value) => value.to_string(),
        ParamValue::Float(value) => value.to_string(),
        ParamValue::Text(value) => quote(value),
    }
}

fn policy_name(policy: NetSecurityPolicy) -> &'static str {
    match policy {
        NetSecurityPolicy::Plain => "plain",
        NetSecurityPolicy::Automatic => "automatic",
        NetSecurityPolicy::Authentication => "authentication",
        NetSecurityPolicy::AuthenticationConfidentiality => "authentication_confidentiality",
    }
}

fn priority_name(priority: ObjectPriority) -> &'static str {
    match priority {
        ObjectPriority::System => "system",
        ObjectPriority::High => "high",
        ObjectPriority::Alarm => "alarm",
        ObjectPriority::Low => "low",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::SourceSpan;

    fn draft() -> ProjectDeviceDraft {
        let net = DraftNet {
            id: NetId("switch".into()),
            address: GroupAddress::from_three_level(1, 0, 1),
            dpt: "1.001".into(),
            security: NetSecurityPolicy::Automatic,
        };
        ProjectDeviceDraft {
            id: ProjectDeviceId("button".into()),
            product: PathBuf::from("products/button.mtxml"),
            address: IndividualAddress::new(1, 1, 10),
            serial: None,
            max_apdu: None,
            parameters: Vec::new(),
            objects: BTreeMap::from([(0, ProjectObjectConfiguration {
                com_object: 0,
                memberships: vec![crate::ObjectMembership {
                    net: net.id.clone(),
                    role: MembershipRole::Primary,
                    span: SourceSpan { start: 0, end: 0 },
                }],
                flags: ObjectFlagOverrides { communication: Some(true), ..Default::default() },
                span: SourceSpan { start: 0, end: 0 },
            })]),
            nets: BTreeMap::from([(net.id.clone(), net)]),
        }
    }

    #[test]
    fn single_device_render_round_trips_through_the_grammar() {
        let source = render_single_device_project(&draft()).expect("draft renders");
        let parsed = AuthoredProject::parse(source).expect("rendered project parses");
        assert_eq!(parsed.devices.len(), 1);
        assert_eq!(parsed.nets.len(), 1);
    }

    #[test]
    fn device_update_preserves_unrelated_comments_and_source() {
        let source = render_single_device_project(&draft()).expect("draft renders");
        let source = source.replace("area 1", "# topology comment\narea 1");
        let project = AuthoredProject::parse(source.clone()).expect("project parses");
        let mut changed = draft();
        changed.max_apdu = Some(40);
        let updated = project.render_device_update(&changed).expect("device updates");
        assert!(updated.contains("# topology comment"));
        assert!(updated.contains("max_apdu 40"));
        assert_eq!(
            &source[..source.find("# topology comment").expect("comment exists")],
            &updated[..updated.find("# topology comment").expect("comment exists")]
        );
    }

    #[test]
    fn net_policy_update_replaces_only_the_policy_token() {
        let source = render_single_device_project(&draft()).expect("draft renders").replace(
            "net switch : 1.001 { security automatic }",
            "net switch : 1.001 {\n    security automatic # keep this comment\n}",
        );
        let project = AuthoredProject::parse(source).expect("project parses");
        let mut changed = draft();
        changed.nets.get_mut(&NetId("switch".into())).expect("net exists").security =
            NetSecurityPolicy::AuthenticationConfidentiality;

        let updated = project.render_device_update(&changed).expect("net policy updates");
        assert!(updated.contains("security authentication_confidentiality # keep this comment"));
    }
}
