//! Secure Application Layer (S-AL) wrapper.
//!
//! Wraps the plain [`ApplicationLayer`] to add KNX Data Secure support.
//!
//! - **Incoming**: Detects Secure Service APDUs (APCI 0x03F1), decrypts/
//!   verifies, populates [`AccessContext`], forwards plaintext to inner AL.
//! - **Outgoing**: When the incoming request was secure, encrypts the
//!   response with the same key before forwarding to the TL.
//!
//! [`ApplicationLayer`]: crate::layers::application::ApplicationLayer
//! [`AccessContext`]: zweidraehte_proto::access::AccessContext

use core::cell::{Cell, RefCell};

use crate::{
    HasSecureIdentity, StackState,
    actor::Request,
    bcus::system_b::{HasExtensionState, HasSecurityState, SecurityFailureType},
    context::layer::HasOutbox,
    definition::StackDefinition,
    layers::application::{ApplicationLayer, ApplicationLayerService, ApplicationLayerServiceResponse},
    objects::tables::{AssociationTable, HasAssociationTable},
    prelude::HasAddressTable,
    router::Layer,
    storage::SequenceNumberStorage,
};
use zweidraehte_proto::access::{AccessContext, AccessSource, ClientRole, SecurityMode};
use zweidraehte_proto::crypto::{ccm, scf::SecureServiceType};
use zweidraehte_proto::messages::{
    apdu::secure::{SecureApduMut, SecureApduRef},
    buffers::{Buffer, MessageBuffer},
    knx::{ApciCode, KnxMessageBuffer, ServiceType, offsets},
};

use crate::logging::warn;

pub mod group_data;
pub(crate) mod outgoing;
pub mod p2p_feature;
mod p2p_security;

pub use group_data::SecureGroupDataProvider;
pub use p2p_feature::{NoP2p, P2pFeature, WithP2p};

// ============================================================================
// Processing result for try_process_secure
// ============================================================================

/// Result of secure frame processing.
pub enum SecureResult {
    /// Forward the (decrypted) message to the inner Application Layer.
    Forward(KnxMessageBuffer<Buffer<'static>>),
    /// Frame was silently dropped (verification failed, etc.).
    Dropped,
    /// A sync response was generated — push directly to outbox.
    SyncResponse(KnxMessageBuffer<Buffer<'static>>),
}

// ============================================================================
// Sequence number helpers
// ============================================================================

/// Convert a 6-byte big-endian sequence number to u64.
pub(super) fn seq_to_u64(seq: &[u8; 6]) -> u64 {
    let mut full = [0u8; 8];
    full[2..8].copy_from_slice(seq);
    u64::from_be_bytes(full)
}

/// Convert a u64 to a 6-byte big-endian sequence number.
pub(super) fn u64_to_seq(val: u64) -> [u8; 6] {
    let full = val.to_be_bytes();
    let mut seq = [0u8; 6];
    seq.copy_from_slice(&full[2..8]);
    seq
}

// ============================================================================
// Outgoing security context — tracks whether to encrypt the response
// ============================================================================

/// Tracks the security context of the current incoming request so that
/// the outgoing response can be encrypted with the same parameters.
#[derive(Clone, Copy)]
struct OutgoingSecurityCtx {
    /// Whether the current request was secure and responses should be encrypted.
    active: bool,
    /// The key to use for encrypting the response.
    key: [u8; 16],
    /// SCF byte for the response (same algorithm/tool flag as request).
    scf_byte: u8,
    /// Source address of the original request (becomes destination of response).
    request_src: u16,
    /// TL outgoing sequence number for connection-oriented responses.
    /// When set, the S-AL pre-sets the TPCI to `DataConnected(seq)` before
    /// encrypting so the CCM B0 block includes the correct TPCI bits.
    outgoing_tl_seq: Option<u8>,
}

impl Default for OutgoingSecurityCtx {
    fn default() -> Self {
        Self { active: false, key: [0u8; 16], scf_byte: 0, request_src: 0, outgoing_tl_seq: None }
    }
}

// ============================================================================
// Pending sync state — tracks an outgoing S-A_Sync.req awaiting response
// ============================================================================

/// State for a pending DUT-initiated sync request.
///
/// When the DUT initiates an S-A_Sync_Req, it stores this state to match
/// and verify the subsequent S-A_Sync_Res from the peer. The sync is
/// considered expired after 6 seconds (spec §5.3.2).
#[derive(Clone, Copy)]
pub(super) struct PendingSyncState {
    /// Individual address of the sync target.
    peer_ia: u16,
    /// Whether this sync uses the tool key (T flag).
    tool_access: bool,
    /// Plaintext challenge generated by the DUT (before encryption).
    challenge: [u8; 6],
    /// Random value used in the challenge encryption.
    random: [u8; 6],
    /// Key used for the sync request (tool key or P2P key).
    key: [u8; 16],
    /// Deadline after which this pending sync expires (6 seconds from send).
    deadline: embassy_time::Instant,
    /// Whether the request was sent as broadcast.
    is_broadcast: bool,
}

// ============================================================================
// SecureApplicationLayer
// ============================================================================

/// Secure Application Layer wrapper.
///
/// Generics:
/// - `SEQ`: sequence number storage backend. Kept separate from the main
///   device config because sequence numbers change on every outgoing
///   secure frame and need wear-resistant storage (e.g., a dedicated
///   flash sector with wear leveling).
/// - `P2P`: [`P2pFeature`] slot selecting whether KNX Data Secure P2P
///   sync (S-A_Sync_Req / S-A_Sync_Res) is compiled in. Defaults to
///   [`NoP2p`]: no SIAT dispatch, no pending-sync tracker, no code —
///   LLVM elides the stubs through monomorphisation. Devices that need
///   P2P pass [`WithP2p`] explicitly.
pub struct SecureApplicationLayer<'a, D: StackDefinition, SEQ: SequenceNumberStorage, P2P: P2pFeature = NoP2p> {
    pub(super) inner: ApplicationLayer<'a, D>,
    /// Security context for encrypting the outgoing response.
    outgoing_ctx: Cell<OutgoingSecurityCtx>,
    /// Borrowed reference to the sequence number storage that lives on
    /// `SecureExtensionState`. Shared with the Security IO augment which
    /// handles PID 59 (PID_SEQUENCE_NUMBER_SENDING) read/write.
    pub(super) seq_storage: &'a RefCell<SEQ>,
    /// Per-instance state owned by the P2P feature slot. For
    /// [`NoP2p`] this is `()` — zero bytes — and the feature trait
    /// methods return `Dropped`/`None` before ever touching it.
    pub(super) p2p_state: P2P::State,
}

impl<'a, D: StackDefinition, SEQ: SequenceNumberStorage, P2P: P2pFeature> SecureApplicationLayer<'a, D, SEQ, P2P> {
    pub fn new(inner: ApplicationLayer<'a, D>, seq_storage: &'a RefCell<SEQ>) -> Self {
        Self {
            inner,
            seq_storage,
            outgoing_ctx: Cell::new(OutgoingSecurityCtx::default()),
            p2p_state: P2P::State::default(),
        }
    }

    pub fn inner_mut(&mut self) -> &mut ApplicationLayer<'a, D> {
        &mut self.inner
    }

    /// Reserve the next sending sequence number.
    ///
    /// Thin wrapper over [`outgoing::reserve_next_seq_nr`] that supplies
    /// the shared `seq_storage`.
    fn next_seq_nr(&self, tool_access: bool) -> Option<[u8; 6]> {
        outgoing::reserve_next_seq_nr(self.seq_storage, tool_access)
    }
}

impl<'a, D: StackDefinition, SEQ: SequenceNumberStorage, P2P: P2pFeature> SecureApplicationLayer<'a, D, SEQ, P2P>
where
    D::State: HasSecureIdentity + HasExtensionState + HasAddressTable + HasAssociationTable,
    <D::State as HasExtensionState>::ES: HasSecurityState,
{
    // ========================================================================
    // GO Security Flag Enforcement
    // ========================================================================

    /// Check whether the received security level matches the GO security flags
    /// for all group objects associated with the given TSAP.
    ///
    /// `received_security_bits` encodes what the frame provides:
    /// - 0x00 = plain (no security)
    /// - 0x01 = authentication only
    /// - 0x03 = authentication + confidentiality
    ///
    /// Returns `true` if the frame should be accepted, `false` if it should
    /// be rejected. The check is **exact match**: the received bits must equal
    /// the GO's required security flag bits (bits 0-1).
    fn check_go_security_flags(&self, tsap: u16, received_security_bits: u8) -> bool {
        let security_state = self.inner.state().extension_state();
        let ast = self.inner.state().ast().borrow();

        for asap in ast.asaps_for_tsap(tsap) {
            // The GO flags table is indexed by 0-based position, written via
            // PID_GO_SECURITY_FLAGS with 1-based property indexing. The ASAP
            // from the association table is the 1-based communication object
            // number, so we subtract 1 to get the 0-based GO flag index.
            let go_index = asap.saturating_sub(1);
            if let Some(go_flag) = security_state.go_security_flags_for(go_index) {
                let required = go_flag & 0x03;
                if required != received_security_bits {
                    return false;
                }
            }
            // If no GO flag entry exists for this ASAP, the GO has no
            // security requirement — accept any security level.
        }

        true
    }

    /// Check GO security flags for a plain (non-secure) group frame.
    ///
    /// At this point the TL has already resolved the destination GA to a TSAP
    /// and stored it in the destination address bytes. We read the TSAP directly
    /// and verify that all associated GOs have security flags = 0x00 (plain allowed).
    /// Returns `true` if the frame should be accepted.
    fn check_plain_group_allowed(&self, msg: &KnxMessageBuffer<Buffer<'static>>) -> bool {
        let buf = msg.buf();
        let tsap = u16::from_be_bytes([buf[offsets::MSG_DEST_ADDR], buf[offsets::MSG_DEST_ADDR + 1]]);
        self.check_go_security_flags(tsap, 0x00)
    }

    /// Try to process an incoming message as a Secure Service APDU.
    fn try_process_secure(&self, mut msg: KnxMessageBuffer<Buffer<'static>>) -> SecureResult {
        let apci = msg.get_apci_code();

        if !matches!(apci, ApciCode::SecureService) {
            // Not secure — clear any pending outgoing security context.
            self.outgoing_ctx.set(OutgoingSecurityCtx::default());

            // For plain group frames, verify that the GO security flags
            // allow plain access. If a GO requires authentication or
            // confidentiality, plain frames must be rejected.
            let st = msg.service_type();
            if matches!(st, ServiceType::T_GroupData_Ind) {
                if !self.check_plain_group_allowed(&msg) {
                    let src = u16::from_be_bytes(msg.get_source_addr().0);
                    let security_state = self.inner.state().extension_state();
                    warn!("S-AL: plain group frame rejected — GO requires security");
                    security_state.log_security_failure(SecurityFailureType::CryptoError, src, &[]);
                    return SecureResult::Dropped;
                }
            }

            return SecureResult::Forward(msg);
        }

        // Don't try to decrypt confirmation frames — they echo our own
        // outgoing encrypted response and would fail MAC verification.
        let st = msg.service_type();
        if matches!(
            st,
            ServiceType::T_Data_Con
                | ServiceType::T_DataUnack_Con
                | ServiceType::T_GroupData_Con
                | ServiceType::T_Broadcast_Con
                | ServiceType::T_SystemBroadcast_Con
        ) {
            return SecureResult::Forward(msg);
        }

        let security_state = self.inner.state().extension_state();
        let src = u16::from_be_bytes(msg.get_source_addr().0);
        let outgoing_tl_seq = msg.outgoing_tl_seq();
        let buf = msg.buf_mut();

        // Parse the secure frame header.
        let secure_ref = match SecureApduRef::parse(buf) {
            Ok(r) => r,
            Err(_) => {
                warn!("S-AL: secure frame too short ({} bytes)", buf.len());
                return SecureResult::Dropped;
            }
        };

        let scf_byte = secure_ref.scf_byte();
        let scf = match secure_ref.scf() {
            Ok(scf) => scf,
            Err(_) => {
                warn!("S-AL: invalid SCF 0x{:02X}", scf_byte);
                security_state.log_security_failure(SecurityFailureType::ScfError, src, &[]);
                return SecureResult::Dropped;
            }
        };
        drop(secure_ref);

        // ================================================================
        // S-A_Sync handling
        // ================================================================

        if scf.service == SecureServiceType::SyncRequest {
            return P2P::process_sync_request(self, msg, scf, scf_byte, src, st);
        }

        if scf.service == SecureServiceType::SyncResponse {
            return P2P::process_sync_response(self, msg, scf, scf_byte, src);
        }

        // From here on, only S-A_Data is handled.
        // Re-parse the secure frame header for data-specific fields.
        let buf = msg.buf_mut();
        let secure_ref = SecureApduRef::parse(buf).expect("already validated length");

        // Early reject: SeqNr == 0 is always invalid per spec.
        // Full per-sender validation happens after MAC verification below.
        let seq_nr = secure_ref.seq_nr();
        if seq_nr == [0u8; 6] {
            warn!("S-AL: sequence number is zero — rejected");
            security_state.log_security_failure(SecurityFailureType::SeqNrError, src, &[]);
            return SecureResult::Dropped;
        }
        let received_mac = secure_ref.mac();
        let addr_type = secure_ref.addr_type();
        let mut ctx = secure_ref.ccm_context(src);
        drop(secure_ref);

        // For group-addressed frames, the TL has replaced the destination GA
        // with the TSAP in MSG_DEST_ADDR. The CCM context was built with the
        // TSAP as `dst`, but the MAC was computed with the original GA. We
        // must restore the original GA for correct MAC verification.
        if addr_type != 0 {
            use crate::objects::tables::AddressTable;
            let tsap = ctx.dst; // Currently holds the TSAP, not the GA.
            let adt = self.inner.state().adt().borrow();
            if let Some(ga) = adt.get_address(tsap) {
                ctx.dst = u16::from_be_bytes(ga.0);
            }
        }

        // Per KNX spec 03/05/01 §6.3.6-8: if the Security IO load state
        // is not "Loaded", security tables (P2P keys, group keys, SIAT) must
        // not be evaluated. Tool Key is independent of load state.
        if !scf.tool_access {
            use crate::objects::tables::LoadState;
            if security_state.security_load_state() != LoadState::Loaded {
                warn!(
                    "S-AL: security tables not loaded (state={:?}), dropping non-tool frame",
                    security_state.security_load_state()
                );
                return SecureResult::Dropped;
            }
        }

        // Per AN158 §2.2.1.5.3.2: tool key access on group communication
        // is forbidden. However, tool key IS allowed on broadcast and system
        // broadcast (spec §5.5.8 Table 10). Only reject tool access when the
        // service type is T_GroupData_Ind (actual group communication).
        if scf.tool_access && matches!(st, ServiceType::T_GroupData_Ind) {
            warn!("S-AL: tool access on group communication rejected");
            security_state.log_security_failure(SecurityFailureType::CryptoError, src, &[]);
            return SecureResult::Dropped;
        }

        // Non-tool P2P communication requires the sender to be in the SIAT.
        if !scf.tool_access && addr_type == 0 {
            if !security_state.is_in_siat(src) {
                warn!("S-AL: sender {:#06X} not in SIAT", src);
                security_state.log_security_failure(SecurityFailureType::RoleError, src, &[]);
                return SecureResult::Dropped;
            }
        }

        // Look up key (and roles for P2P) based on access type.
        let mut p2p_roles: u16 = 0;
        let key = if scf.tool_access {
            // Tool access: use configured tool key, or FDSK as fallback
            // when the device is in factory state (tool key all zeros).
            let tk = security_state.tool_key();
            if tk != [0u8; 16] { tk } else { self.inner.state().fdsk().copied().unwrap_or([0u8; 16]) }
        } else if addr_type != 0 {
            // Group communication: look up group key by TSAP.
            //
            // At this point in the stack, the TL has already resolved the
            // destination group address to a TSAP and stored it in the
            // destination address bytes (via set_connection_nr). We read
            // the TSAP directly instead of re-resolving through the ADT.
            let tsap = u16::from_be_bytes([buf[offsets::MSG_DEST_ADDR], buf[offsets::MSG_DEST_ADDR + 1]]);
            match security_state.group_key_for_index(tsap) {
                Some(k) => k,
                None => {
                    warn!("S-AL: no group key for TSAP {}", tsap);
                    security_state.log_security_failure(SecurityFailureType::CryptoError, src, &[]);
                    return SecureResult::Dropped;
                }
            }
        } else {
            // P2P non-tool: look up key and roles from P2P key table.
            match security_state.p2p_key_for_ia(src) {
                Some((k, roles)) => {
                    p2p_roles = roles;
                    k
                }
                None => {
                    warn!("S-AL: no P2P key for IA {:#06X}", src);
                    security_state.log_security_failure(SecurityFailureType::CryptoError, src, &[]);
                    return SecureResult::Dropped;
                }
            }
        };

        // Decrypt / verify, then collapse to plaintext.
        let mut secure_mut = SecureApduMut::parse(buf).expect("already validated length");

        if scf.confidentiality {
            if ccm::verify_and_decrypt(&key, &ctx, scf_byte, secure_mut.payload_mut(), &received_mac).is_err() {
                warn!("S-AL: MAC verification failed (A+C)");
                security_state.log_security_failure(SecurityFailureType::CryptoError, src, &[]);
                return SecureResult::Dropped;
            }
        } else if ccm::verify_mac_auth_only(&key, &ctx, scf_byte, secure_mut.payload(), &received_mac).is_err() {
            warn!("S-AL: MAC verification failed (auth-only)");
            security_state.log_security_failure(SecurityFailureType::CryptoError, src, &[]);
            return SecureResult::Dropped;
        }

        let new_len = secure_mut.unwrap_to_plaintext();
        buf.set_len(new_len);

        // ================================================================
        // Sequence Number Validation (per spec 03/03/07 §5.3.1)
        // ================================================================
        //
        // After successful MAC verification, compare the received SeqNr
        // against the stored "Last Valid SeqNr" for this sender.
        // Note: SeqNr == 0 was already rejected as an early optimization
        // before MAC verification.
        {
            let seq_nr_val = seq_to_u64(&seq_nr);
            let mut storage = self.seq_storage.borrow_mut();
            let stored = if scf.tool_access {
                storage.load_tool_receiving_seq().ok().flatten()
            } else {
                // For group communication, the "sender" is identified by
                // their individual address (src), not the group address.
                storage.load_receiving_seq(src).ok().flatten()
            };
            let stored_val = stored.map(|s| seq_to_u64(&s)).unwrap_or(0);

            if seq_nr_val > stored_val {
                // Accept: update stored to the received value.
                if scf.tool_access {
                    let _ = storage.save_tool_receiving_seq(&seq_nr);
                } else {
                    let _ = storage.save_receiving_seq(src, &seq_nr);
                }
            } else if seq_nr_val == stored_val {
                // Retransmission: ignore silently (no failure log per spec).
                return SecureResult::Dropped;
            } else {
                // Replay: ignore, log SeqNr failure.
                // The S-AL shall not block further messages from this sender.
                security_state.log_security_failure(SecurityFailureType::SeqNrError, src, &[]);
                return SecureResult::Dropped;
            }
        }

        // ================================================================
        // GO Security Flag Enforcement (group-addressed frames only)
        // ================================================================
        //
        // For non-tool group communication, verify that the received security
        // level exactly matches the GO's required security flags. The rule is
        // exact match: auth-only frames are only accepted by GOs requiring
        // auth-only (flag 0x01), auth+conf by flag 0x03, etc.
        if !scf.tool_access && addr_type != 0 {
            let received_bits = if scf.confidentiality { 0x03 } else { 0x01 };
            // TSAP is in the destination bytes (set by TL's set_connection_nr).
            let tsap = u16::from_be_bytes([buf[offsets::MSG_DEST_ADDR], buf[offsets::MSG_DEST_ADDR + 1]]);
            if !self.check_go_security_flags(tsap, received_bits) {
                warn!("S-AL: GO security flag mismatch for TSAP {} (received={:#04X})", tsap, received_bits);
                security_state.log_security_failure(SecurityFailureType::CryptoError, src, &[]);
                return SecureResult::Dropped;
            }
        }

        // Set outgoing security context so the response gets encrypted.
        self.outgoing_ctx.set(OutgoingSecurityCtx { active: true, key, scf_byte, request_src: src, outgoing_tl_seq });

        // Populate AccessContext.
        let security_mode = if scf.confidentiality { SecurityMode::AuthConf } else { SecurityMode::AuthOnly };
        let role = if scf.tool_access {
            ClientRole::Tool
        } else if addr_type == 0 && p2p_roles != 0 {
            // P2P non-tool with assigned roles from the P2P key table.
            ClientRole::Roles(p2p_roles)
        } else {
            ClientRole::Unlisted
        };
        let mut access_ctx = AccessContext::with_security(0, security_mode, role);
        access_ctx.source_addr = src;
        let _ = buf;
        msg.set_access_source(AccessSource::Explicit(access_ctx));

        SecureResult::Forward(msg)
    }

    // ========================================================================
    // Application request routing (intercepts SyncRequest before inner AL)
    // ========================================================================

    /// Handle an application service request, intercepting sync requests.
    ///
    /// `SyncRequest` is handled here by calling [`initiate_sync`]. All other
    /// requests are forwarded to the inner [`ApplicationLayer`].
    pub fn handle_app_request(&mut self, request: &Request<ApplicationLayerService, ApplicationLayerServiceResponse>) {
        match request.get() {
            ApplicationLayerService::SyncRequest { peer_ia, tool_access, is_broadcast } => {
                if let Some(msg) = P2P::initiate_sync(self, *peer_ia, *tool_access, *is_broadcast) {
                    self.inner.lctx().push_outbox(msg);
                    request.try_reply(ApplicationLayerServiceResponse::SyncInitiated).ok();
                } else {
                    request.try_reply(ApplicationLayerServiceResponse::SyncFailed).ok();
                }
            }
            _ => {
                self.inner.handle_app_request(request);
            }
        }
    }

    /// Encrypt an outgoing message if the current context requires it.
    ///
    /// Takes a plaintext message from the inner AL's outbox and wraps it
    /// in a Secure APDU if the outgoing security context is active.
    fn try_encrypt_outgoing(
        &self,
        mut msg: KnxMessageBuffer<Buffer<'static>>,
    ) -> Option<KnxMessageBuffer<Buffer<'static>>> {
        let ctx = self.outgoing_ctx.get();
        if !ctx.active {
            return Some(msg);
        }

        // Only encrypt downward indications (to TL), not confirmations coming back up.
        let st = msg.service_type();
        let is_downward = matches!(
            st,
            ServiceType::T_Data_Req
                | ServiceType::T_DataUnack_Req
                | ServiceType::T_GroupData_Req
                | ServiceType::T_Broadcast_Req
                | ServiceType::T_SystemBroadcast_Req
        );
        if !is_downward {
            return Some(msg);
        }

        // ============================================================
        // Build the secure frame
        // ============================================================
        //
        // Key selection: for group-addressed responses, look up the
        // outgoing group key by destination TSAP (which is still in
        // MSG_DEST_ADDR as a ConnectionNr). The incoming key
        // (ctx.key) was for the receiving GA's TSAP; the outgoing key
        // may differ when the GO has separate send/receive GAs.
        let tool_access = (ctx.scf_byte & 0x80) != 0;
        let encryption_key = if matches!(st, ServiceType::T_GroupData_Req) && !tool_access {
            let buf = msg.buf();
            let out_tsap = u16::from_be_bytes([buf[offsets::MSG_DEST_ADDR], buf[offsets::MSG_DEST_ADDR + 1]]);
            let security_state = self.inner.state().extension_state();
            security_state.group_key_for_index(out_tsap).unwrap_or(ctx.key)
        } else {
            ctx.key
        };

        let Some(seq_nr) = self.next_seq_nr(tool_access) else {
            // Sequence number overflow — the device must not send any more
            // secure frames. Drop the outgoing message entirely.
            warn!("S-AL: sequence number overflow, dropping outgoing secure frame");
            return None;
        };

        // Device's own address for the CCM B0 source — the NL hasn't
        // filled in MSG_SOURCE_ADDR yet at this point in the outgoing path.
        let src = u16::from_be_bytes(self.inner.state().individual_address().0);
        let adt = self.inner.state().adt().borrow();

        let inputs = outgoing::WrapInputs {
            scf_byte: ctx.scf_byte,
            key: encryption_key,
            src,
            seq_nr,
            outgoing_tl_seq: ctx.outgoing_tl_seq,
            adt: &*adt,
        };

        match outgoing::wrap_outgoing(&mut msg, inputs) {
            Ok(()) => Some(msg),
            Err(outgoing::WrapError::BufferTooSmall) => Some(msg), // Fall back to plaintext (warn already logged).
            Err(outgoing::WrapError::InvalidScf) => {
                // Shouldn't happen — ctx.scf_byte came from an incoming
                // frame we already parsed as valid SCF. Drop defensively.
                warn!("S-AL: SCF byte 0x{:02X} unexpectedly invalid for outgoing wrap", ctx.scf_byte);
                None
            }
        }
    }
}

impl<D: StackDefinition, SEQ: SequenceNumberStorage, P2P: P2pFeature> Layer for SecureApplicationLayer<'_, D, SEQ, P2P>
where
    D::State: HasSecureIdentity + HasExtensionState + HasAddressTable + HasAssociationTable,
    <D::State as HasExtensionState>::ES: HasSecurityState,
{
    const HANDLES: &'static [ServiceType] = ApplicationLayer::<D>::HANDLES;

    fn process(&mut self, msg: KnxMessageBuffer<Buffer<'static>>) {
        match self.try_process_secure(msg) {
            SecureResult::Forward(msg) => {
                // The inner AL pushes directly to the shared outbox. We
                // need to intercept those messages to encrypt them when the
                // security context is active. Swap the shared outbox with
                // a fresh one, let the inner AL push into it, then drain,
                // encrypt, and push into the original outbox.
                use crate::router::Outbox;
                let outbox_cell = &self.inner.lctx().outbox;
                let original = outbox_cell.replace(Outbox::new());
                self.inner.process(msg);
                let mut inner_outbox = outbox_cell.replace(original);

                // Drain the inner outbox, encrypting responses if needed.
                while let Some(out_msg) = inner_outbox.take_next() {
                    if let Some(out_msg) = self.try_encrypt_outgoing(out_msg) {
                        outbox_cell.borrow_mut().push(out_msg);
                    }
                }

                // Flush deferred messages (e.g., GO diagnostics bus telegrams)
                // from the intercepted outbox into the real outbox's deferred
                // queue, encrypting if needed.
                inner_outbox.flush_deferred();
                while let Some(out_msg) = inner_outbox.take_next() {
                    if let Some(out_msg) = self.try_encrypt_outgoing(out_msg) {
                        outbox_cell.borrow_mut().push_deferred(out_msg);
                    }
                }

                // Clear outgoing context after processing.
                self.outgoing_ctx.set(OutgoingSecurityCtx::default());
            }
            SecureResult::SyncResponse(msg) => {
                // Sync response is already fully encrypted — push directly.
                self.inner.lctx().push_outbox(msg);
            }
            SecureResult::Dropped => {
                // Verification failed — silently drop.
            }
        }
    }

    fn next_deadline(&self) -> Option<embassy_time::Instant> {
        self.inner.next_deadline()
    }

    fn poll(&mut self) {
        self.inner.poll();
    }

    fn init(&mut self) {
        self.inner.init();
    }
}
