//! Secure Application Layer (S-AL) wrapper.
//!
//! Wraps the plain [`ApplicationLayer`] to add KNX Data Secure support.
//!
//! - **Incoming**: Detects Secure Service APDUs (APCI 0x03F1), decrypts/
//!   verifies, populates [`AccessContext`], forwards plaintext to inner AL.
//! - **Outgoing**: When the incoming request was secure, encrypts the
//!   response with the same key before forwarding to the TL.
//!
//! [`ApplicationLayer`]: crate::layers::application::ApplicationLayer
//! [`AccessContext`]: zweidraehte_proto::access::AccessContext

use core::cell::{Cell, RefCell};

use crate::{
    HasExtensionState, StackState,
    actor::Request,
    definition::StackDefinition,
    layers::application::{ApplicationLayer, ApplicationLayerService, ApplicationLayerServiceResponse},
    objects::tables::{AssociationTable, HasAssociationTable},
    prelude::HasAddressTable,
    state::{HasSecurityState, SecurityFailureType},
    storage::{SecureDeviceIdentity, SequenceNumberStorage, SiatAccess},
};
use zweidraehte_proto::access::{AccessContext, AccessSource, ClientRole, SecurityMode};
use zweidraehte_proto::address::GroupAddress;
use zweidraehte_proto::crypto::{ccm, scf::SecureServiceType};
use zweidraehte_proto::messages::{
    apdu::{
        network_parameter::NetworkParameterInfoReport,
        secure::{SecureApduMut, SecureApduRef},
    },
    buffers::{Buffer, MessageBuffer},
    builder::MessageBuilder,
    knx::{ApciCode, DestinationAddress, KnxMessageBuffer, Priority, ServiceType, offsets},
};

use crate::logging::{debug, warn};
use crate::objects::tables::{AddressTable, LoadState};
use crate::router::Outbox;
use crate::service::Layer;

pub mod group_data;
pub(crate) mod outgoing;
pub mod p2p_feature;
mod p2p_security;

pub use group_data::SecureGroupDataProvider;
pub use p2p_feature::{NoP2p, P2pFeature, WithP2p};

// ============================================================================
// Processing result for try_process_secure
// ============================================================================

/// Result of secure frame processing.
pub enum SecureResult {
    /// Forward the (decrypted) message to the inner Application Layer.
    Forward(KnxMessageBuffer<Buffer<'static>>),
    /// Frame was silently dropped (verification failed, etc.).
    Dropped,
    /// A sync response was generated — push directly to outbox.
    SyncResponse(KnxMessageBuffer<Buffer<'static>>),
}

// ============================================================================
// Sequence number helpers
// ============================================================================

/// Convert a 6-byte big-endian sequence number to u64.
pub(super) fn seq_to_u64(seq: &[u8; 6]) -> u64 {
    let mut full = [0u8; 8];
    full[2..8].copy_from_slice(seq);
    u64::from_be_bytes(full)
}

/// Convert a u64 to a 6-byte big-endian sequence number.
pub(super) fn u64_to_seq(val: u64) -> [u8; 6] {
    let full = val.to_be_bytes();
    let mut seq = [0u8; 6];
    seq.copy_from_slice(&full[2..8]);
    seq
}

// ============================================================================
// Pending sync state — tracks an outgoing S-A_Sync.req awaiting response
// ============================================================================

/// State for a pending DUT-initiated sync request.
///
/// When the DUT initiates an S-A_Sync_Req, it stores this state to match
/// and verify the subsequent S-A_Sync_Res from the peer. The sync is
/// considered expired after 6 seconds (spec §5.3.2).
#[derive(Clone, Copy)]
pub(super) struct PendingSyncState {
    /// Individual address of the sync target.
    peer_ia: u16,
    /// Whether this sync uses the tool key (T flag).
    tool_access: bool,
    /// Plaintext challenge generated by the DUT (before encryption).
    challenge: [u8; 6],
    /// Key used for the sync request (tool key or P2P key).
    key: [u8; 16],
    /// Deadline after which this pending sync expires (6 seconds from send).
    deadline: embassy_time::Instant,
    /// Whether the request was sent as broadcast.
    is_broadcast: bool,
}

// ============================================================================
// SecureApplicationLayer
// ============================================================================

/// Secure Application Layer wrapper.
///
/// Generics:
/// - `SEQ`: sequence number storage backend. Kept separate from the main
///   device config because sequence numbers change on every outgoing
///   secure frame and need wear-resistant storage (e.g., a dedicated
///   flash sector with wear leveling).
/// - `P2P`: [`P2pFeature`] slot selecting whether KNX Data Secure P2P
///   sync (S-A_Sync_Req / S-A_Sync_Res) is compiled in. Defaults to
///   [`NoP2p`]: no SIAT dispatch, no pending-sync tracker, no code —
///   LLVM elides the stubs through monomorphisation. Devices that need
///   P2P pass [`WithP2p`] explicitly.
pub struct SecureApplicationLayer<
    'a,
    D: StackDefinition,
    SEQ: SequenceNumberStorage + SiatAccess,
    P2P: P2pFeature = NoP2p,
> {
    pub(super) inner: ApplicationLayer<'a, D>,
    /// Borrowed reference to the sequence number storage that lives on
    /// `SecureExtensionState`. Shared with the Security IO augment which
    /// handles PID 59 (PID_SEQUENCE_NUMBER_SENDING) read/write.
    pub(super) seq_storage: &'a RefCell<SEQ>,
    /// Per-instance state owned by the P2P feature slot. For
    /// [`NoP2p`] this is `()` — zero bytes — and the feature trait
    /// methods return `Dropped`/`None` before ever touching it.
    pub(super) p2p_state: P2P::State,
    /// Timestamp of the last outgoing S-A_Sync_Res. Used to enforce
    /// the spec's 1 s rate-limit window, which applies to every sync
    /// response regardless of tool-vs-P2P key usage, so it lives on
    /// the S-AL itself rather than inside `WithP2pState`.
    pub(super) last_sync_response: Cell<Option<embassy_time::Instant>>,
    /// Configured rate-limit window (defaults to 1 s; scaled under the
    /// `conformance` feature). Held here so both the tool-key and P2P
    /// sync-request handlers read from one place.
    pub(super) sync_rate_limit: embassy_time::Duration,
}

impl<'a, D: StackDefinition, SEQ: SequenceNumberStorage + SiatAccess, P2P: P2pFeature>
    SecureApplicationLayer<'a, D, SEQ, P2P>
{
    pub fn new(inner: ApplicationLayer<'a, D>, seq_storage: &'a RefCell<SEQ>) -> Self {
        Self {
            inner,
            seq_storage,
            p2p_state: P2P::State::default(),
            last_sync_response: Cell::new(None),
            sync_rate_limit: p2p_feature::default_sync_rate_limit(),
        }
    }

    pub fn inner_mut(&mut self) -> &mut ApplicationLayer<'a, D> {
        &mut self.inner
    }

    /// Reserve the next sending sequence number.
    ///
    /// Thin wrapper over [`outgoing::reserve_next_seq_nr`] that supplies
    /// the shared `seq_storage`.
    fn next_seq_nr(&self, tool_access: bool) -> Option<[u8; 6]> {
        outgoing::reserve_next_seq_nr(self.seq_storage, tool_access)
    }
}

impl<'a, D: StackDefinition, SEQ: SequenceNumberStorage + SiatAccess, P2P: P2pFeature>
    SecureApplicationLayer<'a, D, SEQ, P2P>
where
    D::State: HasExtensionState + HasAddressTable + HasAssociationTable,
    <D::State as StackState>::Identity: SecureDeviceIdentity,
    <D::State as HasExtensionState>::ES: HasSecurityState,
{
    // ========================================================================
    // GO Security Flag Enforcement
    // ========================================================================

    /// Check whether the received security level matches the GO security flags
    /// for all group objects associated with the given TSAP.
    ///
    /// `received_security_bits` encodes what the frame provides:
    /// - 0x00 = plain (no security)
    /// - 0x01 = authentication only
    /// - 0x03 = authentication + confidentiality
    ///
    /// Returns `true` if the frame should be accepted, `false` if it should
    /// be rejected. The check is **exact match**: the received bits must equal
    /// the GO's required security flag bits (bits 0-1).
    fn check_go_security_flags(&self, tsap: u16, received_security_bits: u8) -> bool {
        let security_state = self.inner.state().extension_state();
        let ast = self.inner.state().ast().borrow();

        for asap in ast.asaps_for_tsap(tsap) {
            // The GO flags table is indexed by 0-based position, written via
            // PID_GO_SECURITY_FLAGS with 1-based property indexing. The ASAP
            // from the association table is the 1-based communication object
            // number, so we subtract 1 to get the 0-based GO flag index.
            let go_index = asap.saturating_sub(1);
            if let Some(go_flag) = security_state.go_security_flags_for(go_index) {
                let required = go_flag & 0x03;
                if required != received_security_bits {
                    return false;
                }
            }
            // If no GO flag entry exists for this ASAP, the GO has no
            // security requirement — accept any security level.
        }

        true
    }

    /// Check GO security flags for a plain (non-secure) group frame.
    ///
    /// At this point the TL has already resolved the destination GA to a TSAP
    /// and stored it in the destination address bytes. We read the TSAP directly
    /// and verify that all associated GOs have security flags = 0x00 (plain allowed).
    /// Returns `true` if the frame should be accepted.
    fn check_plain_group_allowed(&self, msg: &KnxMessageBuffer<Buffer<'static>>) -> bool {
        let buf = msg.buf();
        let tsap = u16::from_be_bytes([buf[offsets::MSG_DEST_ADDR], buf[offsets::MSG_DEST_ADDR + 1]]);
        self.check_go_security_flags(tsap, 0x00)
    }

    // ========================================================================
    // Spontaneous Security Report emission (03/05/01 §6.3.11.4)
    // ========================================================================

    /// Record a security failure and, if `PID_SECURITY_REPORT_CONTROL`
    /// (58) is Enabled and this is the first failure since the tool
    /// last cleared `PID_SECURITY_REPORT` (57), broadcast a spontaneous
    /// `A_NetworkParameter_InfoReport` (APCI 0x3DB) per the management
    /// procedure `DMP_InterfaceObjectInfoReport_RCl`.
    ///
    /// Subsequent failures while bit 0 is already set do **not** re-emit —
    /// the spec ties emission to the 0→1 transition of bit 0 of PID 57.
    /// The tool clears PID 57 via authenticated write; the next failure
    /// then triggers a fresh report.
    fn log_security_failure_and_maybe_report(
        &self,
        failure_type: SecurityFailureType,
        source_addr: u16,
        frame_fragment: &[u8],
    ) {
        let security_state = self.inner.state().extension_state();
        let transitioned = security_state.log_security_failure(failure_type, source_addr, frame_fragment);
        if transitioned && security_state.security_report_enabled() {
            let report = security_state.security_report();
            self.emit_security_report(report);
        }
    }

    /// Build and push a `T_Data_Broadcast` carrying
    /// `A_NetworkParameter_InfoReport` for the Security IO's
    /// PID_SECURITY_REPORT (57).
    ///
    /// Payload layout (03/03/07 §3.2.8, 03/05/01 §6.3.11.4):
    ///   object_type = 0x0011 (Security Interface Object)
    ///   property_id = 57    (PID_SECURITY_REPORT)
    ///   test_info   = 0x00
    ///   test_result = `security_report` byte (DPT_Security_Report)
    fn emit_security_report(&self, security_report: u8) {
        // Security IO type and PID from 03/07/03 (InterfaceObjectType table)
        // and 03/05/01 §6.3 (Security IO property table).
        const SECURITY_IO_TYPE: u16 = 0x0011;
        const PID_SECURITY_REPORT: u8 = 57;

        let payload = [0x00u8, security_report];
        let total_len = NetworkParameterInfoReport::msg_len(payload.len());

        let Some(msg_buf) = self.inner.buffer_manager().try_alloc_with_size(total_len) else {
            warn!("S-AL: no buffer for spontaneous security report");
            return;
        };

        // Broadcast via T_Data_Broadcast (destination 0x0000 as group, the
        // address-type flag in the cEMI ctrl byte distinguishes broadcast
        // from group). Priority = urgent per the management procedure
        // specification (03/05/01 §6.3.11.4). Urgent maps to the 2-bit
        // priority value 10b, which this enum labels `Alarm`
        // (03/03/02 §2.2.3: 00=system, 01=normal, 10=urgent, 11=low).
        //
        // §6.3.11.4 mandates plaintext for the security report broadcast
        // (the report itself is the security-error signalling channel; an
        // unauthenticated party must be able to read it). Stamp Plain
        // explicitly so the `try_encrypt_outgoing` drain leaves it
        // unwrapped even when this fires from inside an outbox-swap
        // window of a secure-incoming flow.
        let msg = MessageBuilder::new_request(
            msg_buf,
            ServiceType::T_Broadcast_Req,
            Priority::Alarm,
            DestinationAddress::Group(GroupAddress::from_bytes(&[0x00, 0x00])),
        )
        .with_required_security(zweidraehte_proto::messages::knx::RequiredSecurity::Plain)
        .with_application(ApciCode::NetworkParameterInfoReport)
        .with_data(|buf| {
            NetworkParameterInfoReport::write(buf, SECURITY_IO_TYPE, PID_SECURITY_REPORT, &payload);
        });

        self.inner.lctx().push_outbox(msg.into_inner());
    }

    /// Try to process an incoming message as a Secure Service APDU.
    fn try_process_secure(&self, mut msg: KnxMessageBuffer<Buffer<'static>>) -> SecureResult {
        let apci = msg.get_apci_code();

        if !matches!(apci, ApciCode::SecureService) {
            // For plain group frames, verify that the GO security flags
            // allow plain access. If a GO requires authentication or
            // confidentiality, plain frames must be rejected.
            let st = msg.service_type();
            if matches!(st, ServiceType::T_GroupData_Ind) {
                if !self.check_plain_group_allowed(&msg) {
                    let src = u16::from_be_bytes(msg.get_source_addr().0);
                    warn!("S-AL: plain group frame rejected — GO requires security");
                    self.log_security_failure_and_maybe_report(SecurityFailureType::CryptoError, src, &[]);
                    return SecureResult::Dropped;
                }
            }

            return SecureResult::Forward(msg);
        }

        // Don't try to decrypt confirmation frames — they echo our own
        // outgoing encrypted response and would fail MAC verification.
        let st = msg.service_type();
        if matches!(
            st,
            ServiceType::T_Data_Con
                | ServiceType::T_DataUnack_Con
                | ServiceType::T_GroupData_Con
                | ServiceType::T_Broadcast_Con
                | ServiceType::T_SystemBroadcast_Con
        ) {
            return SecureResult::Forward(msg);
        }

        let security_state = self.inner.state().extension_state();
        let src = u16::from_be_bytes(msg.get_source_addr().0);
        let outgoing_tl_seq = msg.outgoing_tl_seq();
        let buf = msg.buf_mut();

        // Parse the secure frame header.
        let secure_ref = match SecureApduRef::parse(buf) {
            Ok(r) => r,
            Err(_) => {
                warn!("S-AL: secure frame too short ({} bytes)", buf.len());
                return SecureResult::Dropped;
            }
        };

        let scf_byte = secure_ref.scf_byte();
        let scf = match secure_ref.scf() {
            Ok(scf) => scf,
            Err(_) => {
                warn!("S-AL: invalid SCF 0x{:02X}", scf_byte);
                self.log_security_failure_and_maybe_report(SecurityFailureType::ScfError, src, &[]);
                return SecureResult::Dropped;
            }
        };
        drop(secure_ref);

        // ================================================================
        // S-A_Sync handling
        // ================================================================

        if scf.service == SecureServiceType::SyncRequest {
            return p2p_security::process_sync_request::<D, SEQ, P2P>(self, msg, scf, scf_byte, src, st);
        }

        if scf.service == SecureServiceType::SyncResponse {
            return P2P::process_sync_response(self, msg, scf, scf_byte, src);
        }

        // From here on, only S-A_Data is handled.
        // Re-parse the secure frame header for data-specific fields.
        let buf = msg.buf_mut();
        let secure_ref = SecureApduRef::parse(buf).expect("already validated length");

        // Early reject: SeqNr == 0 is always invalid per spec.
        // Full per-sender validation happens after MAC verification below.
        let seq_nr = secure_ref.seq_nr();
        if seq_nr == [0u8; 6] {
            warn!("S-AL: sequence number is zero — rejected");
            self.log_security_failure_and_maybe_report(SecurityFailureType::SeqNrError, src, &[]);
            return SecureResult::Dropped;
        }
        let received_mac = secure_ref.mac();
        let addr_type = secure_ref.addr_type();
        let mut ctx = secure_ref.ccm_context(src);
        drop(secure_ref);

        // For group-addressed frames, the TL has replaced the destination GA
        // with the TSAP in MSG_DEST_ADDR. The CCM context was built with the
        // TSAP as `dst`, but the MAC was computed with the original GA. We
        // must restore the original GA for correct MAC verification.
        if addr_type != 0 {
            let tsap = ctx.dst; // Currently holds the TSAP, not the GA.
            let adt = self.inner.state().adt().borrow();
            if let Some(ga) = adt.address(tsap) {
                ctx.dst = u16::from_be_bytes(ga.0);
            }
        }

        // Per KNX spec 03/05/01 §6.3.6-8: if the Security IO load state
        // is not "Loaded", security tables (P2P keys, group keys, SIAT) must
        // not be evaluated. Tool Key is independent of load state.
        if !scf.tool_access {
            if security_state.security_load_state() != LoadState::Loaded {
                warn!(
                    "S-AL: security tables not loaded (state={:?}), dropping non-tool frame",
                    security_state.security_load_state()
                );
                return SecureResult::Dropped;
            }
        }

        // Per AN158 §2.2.1.5.3.2: tool key access on group communication
        // is forbidden. However, tool key IS allowed on broadcast and system
        // broadcast (spec §5.5.8 Table 10). Only reject tool access when the
        // service type is T_GroupData_Ind (actual group communication).
        if scf.tool_access && matches!(st, ServiceType::T_GroupData_Ind) {
            warn!("S-AL: tool access on group communication rejected");
            self.log_security_failure_and_maybe_report(SecurityFailureType::CryptoError, src, &[]);
            return SecureResult::Dropped;
        }

        // Non-tool P2P communication requires the sender to be in the SIAT —
        // checked against the storage-layer-owned store the SAL already holds.
        if !scf.tool_access && addr_type == 0 {
            if !self.seq_storage.borrow().siat_contains(src) {
                warn!("S-AL: sender {:#06X} not in SIAT", src);
                self.log_security_failure_and_maybe_report(SecurityFailureType::RoleError, src, &[]);
                return SecureResult::Dropped;
            }
        }

        // Look up key (and roles for P2P) based on access type.
        let mut p2p_roles: u16 = 0;
        let key = if scf.tool_access {
            // Tool access: use configured tool key, or FDSK as fallback
            // when the device is in factory state (tool key all zeros).
            let tk = security_state.tool_key();
            if tk != [0u8; 16] {
                debug!("S-AL: decrypt using configured tool key");
                tk
            } else {
                let fdsk =
                    *<<D::State as StackState>::Identity as SecureDeviceIdentity>::fdsk(self.inner.state().identity());
                debug!("S-AL: decrypt using FDSK fallback (tool key empty)");
                fdsk
            }
        } else if addr_type != 0 {
            // Group communication: look up group key by TSAP.
            //
            // At this point in the stack, the TL has already resolved the
            // destination group address to a TSAP and stored it in the
            // destination address bytes (via set_connection_nr). We read
            // the TSAP directly instead of re-resolving through the ADT.
            let tsap = u16::from_be_bytes([buf[offsets::MSG_DEST_ADDR], buf[offsets::MSG_DEST_ADDR + 1]]);
            match security_state.group_key_for_index(tsap) {
                Some(k) => k,
                None => {
                    warn!("S-AL: no group key for TSAP {}", tsap);
                    self.log_security_failure_and_maybe_report(SecurityFailureType::CryptoError, src, &[]);
                    return SecureResult::Dropped;
                }
            }
        } else {
            // P2P non-tool: look up key and roles from P2P key table.
            match security_state.p2p_key_for_ia(src) {
                Some((k, roles)) => {
                    p2p_roles = roles;
                    k
                }
                None => {
                    warn!("S-AL: no P2P key for IA {:#06X}", src);
                    self.log_security_failure_and_maybe_report(SecurityFailureType::CryptoError, src, &[]);
                    return SecureResult::Dropped;
                }
            }
        };

        // Decrypt / verify, then collapse to plaintext.
        let mut secure_mut = SecureApduMut::parse(buf).expect("already validated length");

        if scf.confidentiality {
            if ccm::verify_and_decrypt(&key, &ctx, scf_byte, secure_mut.payload_mut(), &received_mac).is_err() {
                warn!("S-AL: MAC verification failed (A+C)");
                self.log_security_failure_and_maybe_report(SecurityFailureType::CryptoError, src, &[]);
                return SecureResult::Dropped;
            }
        } else if ccm::verify_mac_auth_only(&key, &ctx, scf_byte, secure_mut.payload(), &received_mac).is_err() {
            warn!("S-AL: MAC verification failed (auth-only)");
            self.log_security_failure_and_maybe_report(SecurityFailureType::CryptoError, src, &[]);
            return SecureResult::Dropped;
        }

        let new_len = secure_mut.unwrap_to_plaintext();
        buf.set_len(new_len);

        // ================================================================
        // Sequence Number Validation (per spec 03/03/07 §5.3.1)
        // ================================================================
        //
        // After successful MAC verification, compare the received SeqNr
        // against the stored "Last Valid SeqNr" for this sender.
        // Note: SeqNr == 0 was already rejected as an early optimization
        // before MAC verification.
        {
            let seq_nr_val = seq_to_u64(&seq_nr);
            let mut storage = self.seq_storage.borrow_mut();
            let stored = if scf.tool_access {
                storage.load_tool_receiving_seq().ok().flatten()
            } else {
                // For group communication, the "sender" is identified by
                // their individual address (src), not the group address.
                storage.load_receiving_seq(src).ok().flatten()
            };
            let stored_val = stored.map(|s| seq_to_u64(&s)).unwrap_or(0);

            if seq_nr_val > stored_val {
                // Accept: update stored to the received value.  A save failure
                // is logged but does not cause the frame to be dropped — the
                // MAC already verified, so the plaintext is genuine; discarding
                // it would break the session.  The worst-case consequence is
                // that the same SeqNr can be replayed until storage recovers.
                if scf.tool_access {
                    if let Err(_e) = storage.save_tool_receiving_seq(&seq_nr) {
                        warn!("S-AL: failed to persist tool receiving SeqNr from {:#06X}", src);
                    }
                } else {
                    if let Err(_e) = storage.save_receiving_seq(src, &seq_nr) {
                        warn!("S-AL: failed to persist receiving SeqNr from {:#06X}", src);
                    }
                }
            } else if seq_nr_val == stored_val {
                // Retransmission: ignore silently (no failure log per spec).
                // Logged at debug so an otherwise-invisible drop is diagnosable
                // (e.g. a tool replaying a SeqNr the device already consumed).
                debug!(
                    "S-AL: dropping retransmission from {:#06X} (tool={}): SeqNr {} == stored {}",
                    src, scf.tool_access, seq_nr_val, stored_val
                );
                return SecureResult::Dropped;
            } else {
                // Replay: ignore, log SeqNr failure.
                // The S-AL shall not block further messages from this sender.
                // Surface the rejection: `log_security_failure_and_maybe_report`
                // only updates the security-state counter, so without this the
                // drop is invisible — a tool stuck on a stale SeqNr (e.g. one
                // behind the value a prior tool/ETS session left in the shared
                // `tool_receiving_seq`) otherwise looks like an unexplained hang.
                warn!(
                    "S-AL: replay rejected from {:#06X} (tool={}): SeqNr {} < stored {}; tool must S-A_Sync_Req",
                    src, scf.tool_access, seq_nr_val, stored_val
                );
                // Drop the seq-storage borrow before the helper call — the
                // helper doesn't touch seq storage today, but releasing
                // the outer `RefCell::borrow_mut` guard here keeps the
                // invariant that only one cell is held across the call.
                drop(storage);
                self.log_security_failure_and_maybe_report(SecurityFailureType::SeqNrError, src, &[]);
                return SecureResult::Dropped;
            }
        }

        // ================================================================
        // GO Security Flag Enforcement (group-addressed frames only)
        // ================================================================
        //
        // For non-tool group communication, verify that the received security
        // level exactly matches the GO's required security flags. The rule is
        // exact match: auth-only frames are only accepted by GOs requiring
        // auth-only (flag 0x01), auth+conf by flag 0x03, etc.
        if !scf.tool_access && addr_type != 0 {
            let received_bits = if scf.confidentiality { 0x03 } else { 0x01 };
            // TSAP is in the destination bytes (set by TL's set_connection_nr).
            let tsap = u16::from_be_bytes([buf[offsets::MSG_DEST_ADDR], buf[offsets::MSG_DEST_ADDR + 1]]);
            if !self.check_go_security_flags(tsap, received_bits) {
                warn!("S-AL: GO security flag mismatch for TSAP {} (received={:#04X})", tsap, received_bits);
                self.log_security_failure_and_maybe_report(SecurityFailureType::CryptoError, src, &[]);
                return SecureResult::Dropped;
            }
        }

        // Drop the outstanding `buf` borrow before stamping `msg`.
        let _ = buf;

        // Stamp the indication with its incoming security context so any
        // response built via `MessageBuilder::respond_to` inherits the
        // same level + tool-access flag automatically. The drain-time
        // path (`try_encrypt_outgoing` → `encrypt_spontaneous`) then
        // looks up the live key and synthesises a fresh SCF —
        // tool-key rotation handled implicitly because the read of
        // `tool_key()` is post-`set_tool_key`. `outgoing_tl_seq` is
        // already set on `msg` by the TL for connected indications.
        let stamp_level = if scf.confidentiality {
            zweidraehte_proto::messages::knx::RequiredSecurity::AuthConf
        } else {
            zweidraehte_proto::messages::knx::RequiredSecurity::Auth
        };
        msg.set_required_security(stamp_level);
        msg.set_tool_access_required(scf.tool_access);
        // `key` / `scf_byte` / `outgoing_tl_seq` are now reconstructed at
        // drain time from the response buffer's stamps; suppress the
        // unused warnings until the upstream parsing code stops binding
        // them.
        let _ = key;
        let _ = scf_byte;
        let _ = outgoing_tl_seq;

        // Populate AccessContext.
        let security_mode = if scf.confidentiality { SecurityMode::AuthConf } else { SecurityMode::AuthOnly };
        let role = if scf.tool_access {
            ClientRole::Tool
        } else if addr_type == 0 && p2p_roles != 0 {
            // P2P non-tool with assigned roles from the P2P key table.
            ClientRole::Roles(p2p_roles)
        } else {
            ClientRole::Unlisted
        };
        let mut access_ctx = AccessContext::with_security(0, security_mode, role);
        access_ctx.source_addr = src;
        msg.set_access_source(AccessSource::Explicit(access_ctx));

        SecureResult::Forward(msg)
    }

    // ========================================================================
    // Application request routing (intercepts SyncRequest before inner AL)
    // ========================================================================

    /// Handle an application service request, intercepting sync requests.
    ///
    /// `SyncRequest` is handled here by calling [`initiate_sync`]. All other
    /// requests are forwarded to the inner [`ApplicationLayer`] inside an
    /// outbox-swap window so any spontaneous outbound frames the inner AL
    /// pushes (e.g. a `T_GroupData_Req` from
    /// [`ApplicationLayer::send_group_value_request`]) flow through
    /// [`Self::try_encrypt_outgoing`] before they hit the shared outbox.
    /// Without the swap the spontaneous send would bypass the S-AL entirely
    /// and go out plaintext even when the originating GO's
    /// `PID_GO_SECURITY_FLAGS` requires Auth/AuthConf.
    pub fn handle_app_request(&mut self, request: &Request<ApplicationLayerService, ApplicationLayerServiceResponse>) {
        match request.get() {
            ApplicationLayerService::SyncRequest { peer_ia, tool_access, is_broadcast } => {
                if let Some(msg) = P2P::initiate_sync(self, *peer_ia, *tool_access, *is_broadcast) {
                    self.inner.lctx().push_outbox(msg);
                    request.try_reply(ApplicationLayerServiceResponse::SyncInitiated).ok();
                } else {
                    request.try_reply(ApplicationLayerServiceResponse::SyncFailed).ok();
                }
            }
            _ => {
                self.with_outbox_swap(|this| this.inner.handle_app_request(request));
            }
        }
    }

    /// Run `f` against the inner AL with the shared outbox swapped for a
    /// fresh one, then drain the captured frames through
    /// [`Self::try_encrypt_outgoing`] back into the real outbox.
    ///
    /// This is the single chokepoint that lets the S-AL inspect every frame
    /// the inner AL emits, regardless of which entry point produced it
    /// (incoming-frame `process`, user `handle_app_request`, lifecycle
    /// `poll` / `init`). Each entry point uses this helper so a future
    /// spontaneous-output surface added to the inner AL automatically gets
    /// the encryption pass without a new swap site.
    fn with_outbox_swap<F: FnOnce(&mut Self)>(&mut self, f: F) {
        let original = {
            let outbox_cell = &self.inner.lctx().outbox;
            outbox_cell.replace(Outbox::new())
        };

        f(self);

        let outbox_cell = &self.inner.lctx().outbox;
        let mut inner_outbox = outbox_cell.replace(original);

        // Drain the captured queue into the real outbox in a single
        // FIFO pass, encrypting where required.
        while let Some(out_msg) = inner_outbox.take_next() {
            if let Some(out_msg) = self.try_encrypt_outgoing(out_msg) {
                outbox_cell.borrow_mut().push(out_msg);
            }
        }
    }

    /// Encrypt an outgoing message based on its `RequiredSecurity` stamp.
    ///
    /// All decisions come from the buffer itself — there is no
    /// side-channel context. Reactive responses inherit their stamp
    /// from the indication via [`MessageBuilder::respond_to`]
    /// (which `try_process_secure` populates after MAC verification);
    /// spontaneous outputs stamp themselves at construction time.
    /// This matches the §5.5.3.x decision trees in 03/03/07: the
    /// AL-side service primitive carries `par_auth` / `par_conf`, and
    /// the S-AL routes accordingly.
    ///
    /// 1. **`Plain` / `Unspecified`** — emit unchanged. `Plain` is the
    ///    explicit plaintext stamp (e.g. spontaneous security report
    ///    per §6.3.11.4, GO-diagnostics direct-write 0x00).
    ///    `Unspecified` is the implicit default for plain incoming
    ///    flows and for non-secure devices.
    /// 2. **`Auth` / `AuthConf`** — encrypt. Key selection is driven
    ///    by `tool_access_required` (live `tool_key()` read for
    ///    reactive responses to tool-access requests, handling
    ///    `set_tool_key` rotation automatically per TSSJ §3.8.13.1)
    ///    or by destination type otherwise (group key by TSAP, P2P
    ///    key by peer IA).
    ///
    /// Confirmations and frames the secure layer never wraps return
    /// unchanged.
    fn try_encrypt_outgoing(
        &self,
        msg: KnxMessageBuffer<Buffer<'static>>,
    ) -> Option<KnxMessageBuffer<Buffer<'static>>> {
        use zweidraehte_proto::messages::knx::RequiredSecurity;

        // Only ever encrypt downward indications. Confirmations come back
        // up the stack as plaintext metadata; never touch them.
        let st = msg.service_type();
        let is_downward = matches!(
            st,
            ServiceType::T_Data_Req
                | ServiceType::T_DataUnack_Req
                | ServiceType::T_GroupData_Req
                | ServiceType::T_Broadcast_Req
                | ServiceType::T_SystemBroadcast_Req
        );
        if !is_downward {
            return Some(msg);
        }

        match msg.required_security() {
            RequiredSecurity::Plain | RequiredSecurity::Unspecified => {
                // Producer asked for plaintext, or no security context
                // was stamped (purely plaintext path: incoming plain
                // frame producing a plain response, or a non-secure
                // device's spontaneous output). Either way, no wrap.
                Some(msg)
            }
            RequiredSecurity::Auth | RequiredSecurity::AuthConf => self.encrypt_spontaneous(msg),
        }
    }

    /// Encrypt a spontaneous outbound message stamped with explicit
    /// `Auth` / `AuthConf` security.
    ///
    /// Unlike the reactive path, there is no incoming SCF to inherit from:
    /// we synthesise the SCF from the requested level and the destination
    /// type, and select the key from the appropriate table:
    ///
    /// - `T_GroupData_Req` → group key by destination TSAP (still a
    ///   ConnectionNr in `MSG_DEST_ADDR`; the TL replaces it with the GA
    ///   later, but `wrap_outgoing` reverse-resolves the GA via the ADT
    ///   for the CCM context).
    /// - `T_Data_Req` / `T_DataUnack_Req` (P2P) → P2P key by destination
    ///   IA. P2P entries imply Auth+Conf; if a caller stamps `Auth` on a
    ///   P2P frame we honour it but the spec convention is AuthConf.
    /// - `T_Broadcast_Req` / `T_SystemBroadcast_Req` → not supported here
    ///   yet (no spontaneous secure broadcast surfaces today; the security
    ///   report is `Plain`). Falls back to plaintext with a warning so we
    ///   don't silently drop the message.
    ///
    /// Returns `None` only on seqnr overflow (per spec the device must
    /// stop sending secure frames). On any other failure (no key, buffer
    /// too small) the message is returned unchanged so the receiver — if
    /// any — can at least see the plaintext attempt; this matches the
    /// reactive path's `BufferTooSmall` fallback. The drop-vs-fallback
    /// trade-off is deliberate: silently dropping a spontaneous send
    /// would be invisible to the originating application, while sending
    /// plaintext is visible on the bus and a captured trace immediately
    /// surfaces the misconfiguration.
    fn encrypt_spontaneous(
        &self,
        mut msg: KnxMessageBuffer<Buffer<'static>>,
    ) -> Option<KnxMessageBuffer<Buffer<'static>>> {
        use zweidraehte_proto::crypto::scf::{SecureServiceType, SecurityControlField};
        use zweidraehte_proto::messages::knx::RequiredSecurity;

        let st = msg.service_type();
        let level = msg.required_security();
        debug_assert!(matches!(level, RequiredSecurity::Auth | RequiredSecurity::AuthConf));

        let security_state = self.inner.state().extension_state();

        // ----------------------------------------------------------------
        // Resolve key + tool_access
        // ----------------------------------------------------------------
        // If the buffer was stamped with `tool_access_required` (set by
        // `try_process_secure` for incoming tool-access frames and
        // propagated to responses by `respond_to`), the key is the
        // current tool key — read live so a `set_tool_key` call during
        // the inner AL's processing of the request is reflected in the
        // response (TSSJ §3.8.13.1).
        let (key, tool_access) = if msg.tool_access_required() {
            (security_state.tool_key(), true)
        } else {
            match st {
                ServiceType::T_GroupData_Req => {
                    let buf = msg.buf();
                    let tsap = u16::from_be_bytes([buf[offsets::MSG_DEST_ADDR], buf[offsets::MSG_DEST_ADDR + 1]]);
                    match security_state.group_key_for_index(tsap) {
                        Some(k) => (k, false),
                        None => {
                            warn!(
                                "S-AL: spontaneous group send to TSAP {} requires security but no group key configured — sending plaintext",
                                tsap
                            );
                            return Some(msg);
                        }
                    }
                }
                ServiceType::T_Data_Req | ServiceType::T_DataUnack_Req => {
                    // For an individual-addressed P2P send the destination
                    // bytes hold the peer IA verbatim (not a TSAP — TSAP-style
                    // resolution applies only to group services).
                    let buf = msg.buf();
                    let peer_ia = u16::from_be_bytes([buf[offsets::MSG_DEST_ADDR], buf[offsets::MSG_DEST_ADDR + 1]]);
                    match security_state.p2p_key_for_ia(peer_ia) {
                        Some((k, _roles)) => (k, false),
                        None => {
                            warn!(
                                "S-AL: spontaneous P2P send to {:#06X} requires security but no P2P key configured — sending plaintext",
                                peer_ia
                            );
                            return Some(msg);
                        }
                    }
                }
                ServiceType::T_Broadcast_Req | ServiceType::T_SystemBroadcast_Req => {
                    // No non-tool spontaneous secure broadcast surface
                    // exists today (the tool-access reactive path covers
                    // any secure broadcast response). Fall back to
                    // plaintext + warn so the omission is visible.
                    warn!("S-AL: spontaneous secure broadcast (st={:?}) not yet supported — sending plaintext", st);
                    return Some(msg);
                }
                _ => return Some(msg),
            }
        };

        // ----------------------------------------------------------------
        // Synthesise SCF and reserve seqnr
        // ----------------------------------------------------------------
        let scf = SecurityControlField {
            service: SecureServiceType::Data,
            // System broadcast SCF bit is set only on T_SystemBroadcast_Req
            // wrappings (which we currently fall back from above). The
            // distinction maps to wire framing, not to which key we used.
            system_broadcast: matches!(st, ServiceType::T_SystemBroadcast_Req),
            confidentiality: matches!(level, RequiredSecurity::AuthConf),
            tool_access,
        };
        let scf_byte = scf.encode();

        let Some(seq_nr) = self.next_seq_nr(tool_access) else {
            warn!("S-AL: sequence number overflow, dropping spontaneous secure frame");
            return None;
        };

        debug!(
            "S-AL: encrypt spontaneous {:?} with key[0..2]={:02x}{:02x} (tool={}, scf=0x{:02x})",
            st, key[0], key[1], tool_access, scf_byte
        );

        let src = u16::from_be_bytes(self.inner.state().individual_address().0);
        let adt = self.inner.state().adt().borrow();

        let inputs = outgoing::WrapInputs {
            scf_byte,
            key,
            src,
            seq_nr,
            // Connection-oriented reactive responses inherit the TL seq
            // from the indication via `respond_to`; spontaneous group/
            // broadcast sends carry `None`. Both cases just read what
            // the buffer was stamped with.
            outgoing_tl_seq: msg.outgoing_tl_seq(),
            adt: &*adt,
        };

        match outgoing::wrap_outgoing(&mut msg, inputs) {
            Ok(()) => Some(msg),
            Err(outgoing::WrapError::BufferTooSmall) => Some(msg),
            Err(outgoing::WrapError::InvalidScf) => {
                // We just constructed the SCF ourselves — getting here
                // means a bug above. Drop defensively rather than ship a
                // garbled frame.
                warn!("S-AL: synthesised SCF 0x{:02X} unexpectedly invalid", scf_byte);
                None
            }
        }
    }
}

impl<D: StackDefinition, SEQ: SequenceNumberStorage + SiatAccess, P2P: P2pFeature> Layer<D>
    for SecureApplicationLayer<'_, D, SEQ, P2P>
where
    D::State: HasExtensionState + HasAddressTable + HasAssociationTable,
    <D::State as StackState>::Identity: SecureDeviceIdentity,
    <D::State as HasExtensionState>::ES: HasSecurityState,
{
    const HANDLES: &'static [ServiceType] = <ApplicationLayer<'_, D> as Layer<D>>::HANDLES;

    fn init(&mut self) {
        // The inner AL's `init()` may queue ROI reads up front. The
        // same requirement applies: stamp + encrypt.
        self.with_outbox_swap(|this| Layer::<D>::init(&mut this.inner));
    }

    fn next_deadline(&self) -> Option<embassy_time::Instant> {
        Layer::<D>::next_deadline(&self.inner)
    }

    fn poll(&mut self) {
        // Read-on-init reads (`A_GroupValue_Read.req`) and any other
        // spontaneous emissions originating from the inner AL's poll
        // loop need the same encryption pass that frame-driven sends
        // get.
        self.with_outbox_swap(|this| Layer::<D>::poll(&mut this.inner));
    }

    fn process(&mut self, msg: KnxMessageBuffer<Buffer<'static>>) {
        match self.try_process_secure(msg) {
            SecureResult::Forward(msg) => {
                // Run the inner AL inside the same outbox-swap window
                // the spontaneous-output sites (`init`, `poll`,
                // `handle_app_request`) use. The indication has been
                // stamped with its incoming security context (level +
                // tool-access flag); `MessageBuilder::respond_to`
                // propagates these onto each response buffer, and
                // `try_encrypt_outgoing` reads them at drain time.
                // Tool-key rotation falls out for free: the encrypt
                // path reads `tool_key()` after `set_tool_key` has
                // returned, so the WriteConRes for PID_TOOL_KEY
                // encrypts with the newly-set key (TSSJ §3.8.13.1).
                self.with_outbox_swap(|this| Layer::<D>::process(&mut this.inner, msg));
            }
            SecureResult::SyncResponse(msg) => {
                // Sync response is already fully encrypted — push
                // directly.
                self.inner.lctx().push_outbox(msg);
            }
            SecureResult::Dropped => {
                // Verification failed — silently drop.
            }
        }
    }
}
