[package]
name = "zweidraehte"
version = "0.1.0"
edition = "2024"

[dependencies]
zerocopy = { workspace = true }
const-bitfield = { workspace = true }
const-default = { workspace = true }
paste = { workspace = true }
static_cell = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
embassy-sync = { workspace = true }
embassy-futures = { workspace = true }
defmt = { workspace = true, optional = true }
log = { workspace = true, optional = true }


[features]
defmt = ["dep:defmt"]
log = ["dep:log"]
