[package]
name = "zweidraehte"
version = "0.1.0"
edition = "2024"

[dependencies]
platform = { path = "../platform", features = ["log", "linux"] }

zerocopy = { workspace = true }
#const-bitfield = { workspace = true }
const-default = { workspace = true }
paste = { workspace = true }
static_cell = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
embassy-sync = { workspace = true }
embassy-futures = { workspace = true }
embassy-time = { workspace = true }
defmt = { workspace = true, optional = true }
log = { workspace = true, optional = true }
embedded-io-async = { workspace = true }
pin-project = { workspace = true }
heapless = { workspace = true }
replace_with = { workspace = true }

[dev-dependencies]
test-case = { workspace = true }

[features]
defmt = ["dep:defmt"]
log = ["dep:log"]
test-util = []
std = []
usb = ["std", "dep:async-hid", "dep:futures-lite"]

[target.'cfg(any(target_os = "linux", target_os = "macos", target_os = "windows"))'.dependencies]
async-hid = { workspace = true, optional = true }
futures-lite = { workspace = true, optional = true }
