[package]
name = "devices"
version = "0.1.0"
edition = "2024"

[dependencies]
zweidraehte-device = { path = "../../crates/zweidraehte-device", default-features = false }
zweidraehte-proto = { path = "../../crates/zweidraehte-proto", default-features = false }
zweidraehte-util = { path = "../../crates/zweidraehte-util" }
const-default = { workspace = true }
zerocopy = { workspace = true }
serde = { workspace = true }
zweidraehte-knxprod = { path = "../../crates/zweidraehte-knxprod", optional = true }
env_logger = { workspace = true, optional = true }
embassy-time.workspace = true

[features]
default = []
knxprod = ["dep:zweidraehte-knxprod"]
gen = ["knxprod", "dep:env_logger"]
defmt = ["zweidraehte-device/defmt", "zweidraehte-proto/defmt"]
log = ["zweidraehte-device/log", "zweidraehte-proto/log"]

[[bin]]
name = "gen_light_switch_mtxml"
path = "src/gen_light_switch_mtxml.rs"
required-features = ["gen"]

[[bin]]
name = "gen_ip_interface_mtxml"
path = "src/gen_ip_interface_mtxml.rs"
required-features = ["gen"]
