[package]
name = "testutil"
version = "0.1.0"
edition = "2024"

[dependencies]
zweidraehte-device = { path = "../crates/zweidraehte-device", features = ["log", "linux", "knxip", "tp1", "usb"] }
knx-conformance = { path = "../conformance" }
zweidraehte-platform = { path = "../crates/zweidraehte-platform", features = ["log", "linux"] }
zweidraehte-knxprod = { path = "../crates/zweidraehte-knxprod" }
embassy-sync = { workspace = true, features = ["std"] }
embassy-executor = { workspace = true, features = ["arch-std", "executor-thread"] }
embassy-time = { workspace = true, features = ["std"] }
embassy-futures = { workspace = true }

const-default = { workspace = true }
static_cell = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }

embedded-io-async = { workspace = true }


env_logger = { workspace = true }
log = { workspace = true }
chrono = { workspace = true }
quick-xml = { workspace = true }
base64 = { workspace = true }
regex = { workspace = true }
async-hid = { workspace = true }
futures-lite = { workspace = true }
libc = { workspace = true }

[[bin]]
name = "testutil"
path = "src/main.rs"

[[bin]]
name = "tpuart"
path = "src/tpuart.rs"

[[bin]]
name = "knxip"
path = "src/knxip.rs"

[[bin]]
name = "stack_knxip"
path = "src/stack_knxip.rs"

[[bin]]
name = "busmon"
path = "src/busmon.rs"

[[bin]]
name = "usb_test"
path = "src/usb_test.rs"

[[bin]]
name = "seqno_test"
path = "src/seqno_test.rs"

[[bin]]
name = "stack_system_b"
path = "src/stack_system_b.rs"

[[bin]]
name = "gen_mtxml"
path = "src/gen_mtxml.rs"

[[bin]]
name = "gen_mdt_mtxml"
path = "src/gen_mdt_mtxml.rs"

[[bin]]
name = "compare_programs"
path = "src/compare_programs.rs"

[[bin]]
name = "gen_module_mtxml"
path = "src/gen_module_mtxml.rs"

