//! Stack definition for the Linux-hosted demo device.
//!
//! Binds the transport-agnostic [`devices::system_b_demo`] definition to
//! this target's transport and platform: KNX/IP over the Linux socket
//! stack, with the read-only [`LinuxIpPlatform`] reporting the host's
//! actual network configuration (the OS owns networking, so
//! `apply_ip_config` is a no-op).

use devices::system_b_demo::{DEVICE_DESCRIPTOR, DemoParams, comm_objs};
use zweidraehte_device::bcus::system_b::{IpExtensionFor, IpStateFor};
use zweidraehte_device::layers::linklayers::knxip::{KnxNetIpBuilder, KnxNetIpDefinition, features::KnxIpDeviceTcp};
use zweidraehte_device::layers::transport::TlStyle;
use zweidraehte_device::prelude::*;
use zweidraehte_platform::{LinuxIpPlatform, LinuxIpTransport};

/// Unified state type. Table sizes derive from `DEVICE_DESCRIPTOR`
/// through the `SystemBStackDefinition` associated consts.
pub type DemoState = IpStateFor<DemoStack, KnxIpDeviceTcp>;

#[derive(Debug, Clone, Copy)]
pub struct DemoStack;

// IP-specific link-layer bill of materials. `KnxIpDeviceTcp` is a
// routing device with no tunneling, so `TUNNEL_CAPACITY = 0` and the
// derived defaults for `MAX_TCP_*` collapse to 0. `MAX_UDP_SOCKETS`
// stays at the trait default of 2 (discovery + routing share one
// multicast socket; unicast control wants the second).
impl KnxNetIpDefinition for DemoStack {
    type Transport = LinuxIpTransport;
    type Features = KnxIpDeviceTcp;
}

// The always-identical System B stack shell (StateInit/Mem, create_state, the
// InterfaceObjects/Augments GATs and the two `create_*` bodies, plus the empty
// `SystemBStackDefinition` impl) is generated by `system_b_standard_stack!`;
// only the device-specific bill of materials is spelled out here.
zweidraehte_device::system_b_standard_stack! {
    stack: DemoStack,
    device: &DEVICE_DESCRIPTOR,
    tl_style: TlStyle::Style1,
    params: DemoParams,
    com_objects: comm_objs::DemoComObjects,
    link_layer_builder: KnxNetIpBuilder<DemoStack>,
    platform: LinuxIpPlatform,
    extension_state: IpExtensionFor<KnxIpDeviceTcp>,
    state: DemoState,
    al_extensions: (
        zweidraehte_device::layers::application::services::SystemBAlServices,
        zweidraehte_device::layers::application::services::DomainAddressService,
    ),
    layer_builder: InsecureIpDeviceBuilder,
}
