[package]
name = "zweidraehte-ets"
version = "0.1.0"
edition = "2024"
authors = ["Andreas Galauner <andreas@galauner.de>"]
license = "AGPL-3.0-only"
description = "Proc-macros for KNX ETS parameter export"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
